export const topStudents = [
  { id: 1,  name: "ณัฐพล วิริยะกุล",      field: "วิศวกรรมหุ่นยนต์",        year: "4", award: "🥇 ชนะเลิศ IEEE Thailand 2025",          awardColor: "bg-amber-400 text-white",   email: "nattaphon.w@student.kosen.ac.th",  project: "ระบบหุ่นยนต์เคลื่อนที่อัตโนมัติสำหรับโลจิสติกส์ในโรงงานอุตสาหกรรม" },
  { id: 2,  name: "พิมพ์ชนก สุขสวัสดิ์",  field: "วิศวกรรมอิเล็กทรอนิกส์",  year: "3", award: "🥈 รองชนะเลิศ NECTEC 2025",             awardColor: "bg-slate-500 text-white",   email: "pimchanok.s@student.kosen.ac.th",  project: "วงจรขยายสัญญาณความถี่สูงสำหรับระบบสื่อสาร 5G" },
  { id: 3,  name: "ธนวัฒน์ อินทรชิต",     field: "วิศวกรรมเคมี",             year: "5", award: "📄 Best Paper KOSEN-ASEAN 2025",         awardColor: "bg-violet-600 text-white",  email: "thanawat.i@student.kosen.ac.th",   project: "การพัฒนาตัวเร่งปฏิกิริยาชีวภาพสำหรับการผลิตพลังงานทดแทน" },
  { id: 4,  name: "สุภาภรณ์ แก้วประดิษฐ์", field: "วิศวกรรมโยธา",            year: "4", award: "🌱 JICA Young Innovator 2024",           awardColor: "bg-emerald-600 text-white", email: "supaporn.k@student.kosen.ac.th",   project: "แบบจำลองโครงสร้างสะพานต้านแผ่นดินไหวด้วยวัสดุผสมน้ำหนักเบา" },
  { id: 5,  name: "กิตติภูมิ ตันติวรรณ",  field: "วิศวกรรมวัสดุ",            year: "3", award: "🏅 Science Fair Gold Medal 2024",        awardColor: "bg-orange-500 text-white",  email: "kittiphum.t@student.kosen.ac.th",  project: "วัสดุนาโนคอมโพสิตสำหรับการดูดซับคลื่นแม่เหล็กไฟฟ้า" },
  { id: 6,  name: "วรรณิษา ดีสม",         field: "วิศวกรรมคอมพิวเตอร์",     year: "4", award: "🥇 ชนะเลิศ ICPC Thailand 2024",         awardColor: "bg-amber-400 text-white",   email: "wannisa.d@student.kosen.ac.th",    project: "ระบบตรวจจับการโจมตีไซเบอร์แบบ Real-time ด้วย Machine Learning" },
  { id: 7,  name: "ปิยะพงษ์ แสงทอง",      field: "วิศวกรรมไฟฟ้า",            year: "5", award: "🏆 Thailand Young Scientist 2024",       awardColor: "bg-blue-600 text-white",    email: "piyaphong.s@student.kosen.ac.th",  project: "ระบบจัดการพลังงานไฟฟ้าอัจฉริยะสำหรับอาคารประหยัดพลังงาน" },
  { id: 8,  name: "ชนม์นิภา รุ่งเรือง",   field: "วิศวกรรมสิ่งแวดล้อม",     year: "3", award: "🌏 ASEAN Green Innovation Award 2024",  awardColor: "bg-teal-600 text-white",    email: "chonnipa.r@student.kosen.ac.th",   project: "เทคโนโลยีบำบัดน้ำเสียจากภาคอุตสาหกรรมด้วยพืชน้ำชีวภาพ" },
  { id: 9,  name: "ภาณุวัฒน์ จิตรดี",     field: "วิศวกรรมอุตสาหการ",       year: "4", award: "📐 Best Design KOSEN Expo 2023",        awardColor: "bg-rose-600 text-white",    email: "panuwat.j@student.kosen.ac.th",    project: "การออกแบบสายการผลิตอัตโนมัติด้วยหลัก Lean Manufacturing" },
  { id: 10, name: "อารีรัตน์ พุ่มไพร",    field: "วิศวกรรมชีวการแพทย์",     year: "5", award: "🔬 NSTDA Junior Award 2023",            awardColor: "bg-pink-600 text-white",    email: "areerat.p@student.kosen.ac.th",    project: "อุปกรณ์ตรวจวัดระดับน้ำตาลในเลือดแบบไม่รุกล้ำด้วยเซนเซอร์อินฟราเรด" },
];
