export const DEFAULT_BANNERS = [
  {
    id: "BNR001",
    layout: "hero",
    eyebrow: "เกี่ยวกับโครงการ THAI-KOSEN",
    headline: "โครงการ Thai-KOSEN",
    body: "โครงการ KOSEN ประเทศไทย คือหลักสูตรวิศวกรรมศาสตร์ 5 ปีที่ผสมผสานแนวทางการเรียนแบบญี่ปุ่น ผลิตวิศวกรคุณภาพสูงที่พร้อมทำงานจริงทันทีหลังสำเร็จการศึกษา",
    ctaLabel: "อ่านรายละเอียดเพิ่มเติม",
    ctaHref: "/about",
    secondaryLabel: "ติดต่อสอบถาม",
    secondaryHref: "/contact",
    image: "/banners/banner1.jpg",
    imagePosition: "center",
    badge: "",
    status: "active",
    order: 1,
  },
  {
    id: "BNR002",
    layout: "news-single",
    eyebrow: "",
    headline: "",
    body: "",
    badge: "",
    newsId: "NEWS001",
    ctaLabel: "อ่านข่าวเต็ม",
    ctaHref: "/news/NEWS001",
    secondaryLabel: "",
    secondaryHref: "",
    image: "/banners/banner_news001.jpg",
    imagePosition: "center",
    status: "active",
    order: 2,
  },
  {
    id: "BNR003",
    layout: "news-single",
    eyebrow: "",
    headline: "",
    body: "",
    badge: "",
    newsId: "NEWS011",
    ctaLabel: "อ่านข่าวเต็ม",
    ctaHref: "/news/NEWS011",
    secondaryLabel: "",
    secondaryHref: "",
    image: "/banners/banner_news011.jpg",
    imagePosition: "center top",
    status: "active",
    order: 4,
  },
  {
    id: "BNR004",
    layout: "news-single",
    eyebrow: "",
    headline: "",
    body: "",
    badge: "",
    newsId: "NEWS009",
    ctaLabel: "อ่านข่าวเต็ม",
    ctaHref: "/news/NEWS009",
    secondaryLabel: "",
    secondaryHref: "",
    image: "/banners/banner_news009.jpg",
    imagePosition: "center",
    status: "active",
    order: 3,
  },
];

export const BANNER_STORAGE_KEY = "kosen_banners";
export const BANNER_SEED_KEY   = "kosen_banners_seed";
export const BANNER_SEED_VER   = `v${DEFAULT_BANNERS.length}r10`;
