export const DEFAULT_COMPANIES = [
  {
    id: "COM-001",
    name: "บริษัท โตโยต้า มอเตอร์ ประเทศไทย จำกัด",
    nameEn: "Toyota Motor Thailand Co., Ltd.",
    industry: "ยานยนต์",
    type: "บริษัทจำกัด",
    country: "ไทย",
    province: "สมุทรปราการ",
    address: "186/1 ถ.สุขุมวิท ต.บางปู อ.เมือง จ.สมุทรปราการ 10280",
    website: "https://www.toyota.co.th",
    linkedin: "https://linkedin.com/company/toyota-motor-thailand",
    contactName: "คุณสมศรี วงศ์ทอง",
    contactEmail: "hr@toyota.co.th",
    contactTel: "02-386-1234",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2027-03-31",
    openPositions: 5,
    description: "ผู้ผลิตยานยนต์ชั้นนำ มีโรงงานผลิตในไทยกว่า 3 แห่ง เปิดรับนักศึกษาฝึกงานสาขาวิศวกรรมเครื่องกลและอุตสาหการ",
    note: "",
  },
  {
    id: "COM-002",
    name: "บริษัท เดลต้า อีเลคโทรนิคส์ (ประเทศไทย) จำกัด (มหาชน)",
    nameEn: "Delta Electronics (Thailand) PCL.",
    industry: "อิเล็กทรอนิกส์",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "สมุทรปราการ",
    address: "909 ถ.บางนา-ตราด ต.บางนา กรุงเทพฯ 10260",
    website: "https://www.delta-thailand.com",
    linkedin: "https://linkedin.com/company/delta-electronics-thailand",
    contactName: "คุณวิชัย ประสิทธิ์",
    contactEmail: "recruit@delta.co.th",
    contactTel: "02-709-2800",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2026-12-31",
    openPositions: 4,
    description: "ผู้ผลิตอุปกรณ์อิเล็กทรอนิกส์กำลังและระบบพลังงาน เปิดรับวิศวกรรมไฟฟ้าและอิเล็กทรอนิกส์",
    note: "",
  },
  {
    id: "COM-003",
    name: "บริษัท เอสซีบี เทคเอกซ์ จำกัด",
    nameEn: "SCB Tech X Co., Ltd.",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "9 รัชดาภิเษก จตุจักร กรุงเทพฯ 10900",
    website: "https://www.scbtechx.io",
    linkedin: "https://linkedin.com/company/scb-tech-x",
    contactName: "คุณณัฐพร สุวรรณ",
    contactEmail: "talent@scbtechx.io",
    contactTel: "02-544-7000",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2027-06-30",
    openPositions: 6,
    description: "บริษัทเทคโนโลยีของ SCB เน้น Fintech, AI และ Data Engineering เปิดรับวิศวกรรมคอมพิวเตอร์และ IT",
    note: "",
  },
  {
    id: "COM-004",
    name: "บริษัท พีทีที โกลบอล เคมิคอล จำกัด (มหาชน)",
    nameEn: "PTT Global Chemical PCL.",
    industry: "เคมีและวัสดุ",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "ระยอง",
    address: "555/1 ศูนย์เอนเนอร์ยี่คอมเพล็กซ์ อาคาร A วิภาวดีรังสิต กรุงเทพฯ 10900",
    website: "https://www.pttgcgroup.com",
    linkedin: "https://linkedin.com/company/ptt-global-chemical",
    contactName: "คุณประภาส ชัยสิทธิ์",
    contactEmail: "intern@pttgc.com",
    contactTel: "02-265-8080",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2026-09-30",
    openPositions: 3,
    description: "ผู้นำด้านปิโตรเคมีในภูมิภาค เปิดรับสาขาวิศวกรรมเคมี เครื่องกล และสิ่งแวดล้อม",
    note: "",
  },
  {
    id: "COM-005",
    name: "บริษัท อิตาเลียนไทย ดีเวล๊อปเมนต์ จำกัด (มหาชน)",
    nameEn: "Italian-Thai Development PCL.",
    industry: "ก่อสร้างและโยธา",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "2034/132 ถ.เพชรบุรีตัดใหม่ บางกะปิ กรุงเทพฯ 10310",
    website: "https://www.itd.co.th",
    linkedin: "https://linkedin.com/company/italian-thai-development",
    contactName: "คุณสุชาติ ดีมาก",
    contactEmail: "hr@itd.co.th",
    contactTel: "02-716-1600",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2026-06-30",
    openPositions: 4,
    description: "ผู้รับเหมาก่อสร้างขนาดใหญ่ เน้นโครงสร้างพื้นฐานและโยธา เปิดรับวิศวกรรมโยธาและเครื่องกล",
    note: "",
  },
  {
    id: "COM-006",
    name: "ศูนย์เทคโนโลยีอิเล็กทรอนิกส์และคอมพิวเตอร์แห่งชาติ (NECTEC)",
    nameEn: "National Electronics and Computer Technology Center (NECTEC)",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "หน่วยงานวิจัย",
    country: "ไทย",
    province: "ปทุมธานี",
    address: "112 อุทยานวิทยาศาสตร์ประเทศไทย คลองหลวง ปทุมธานี 12120",
    website: "https://www.nectec.or.th",
    linkedin: "https://linkedin.com/company/nectec",
    contactName: "ดร. วรรณิดา รักดี",
    contactEmail: "internship@nectec.or.th",
    contactTel: "02-564-6900",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2028-03-31",
    openPositions: 3,
    description: "หน่วยงานวิจัยด้าน IT และอิเล็กทรอนิกส์ของประเทศ เปิดรับนักศึกษาทำวิจัยด้าน AI, IoT และ Embedded Systems",
    note: "",
  },
  {
    id: "COM-007",
    name: "บริษัท ไลน์แมน วงใน จำกัด",
    nameEn: "LINE MAN Wongnai Co., Ltd.",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "อาคาร Wave Place ชั้น 9 วิทยุ ลุมพินี กรุงเทพฯ 10330",
    website: "https://www.lineman.co.th",
    linkedin: "https://linkedin.com/company/line-man-wongnai",
    contactName: "คุณพิมพ์ใจ สุขใจ",
    contactEmail: "intern@linemanwongnai.com",
    contactTel: "02-030-0080",
    status: "ร่วมมือ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 5,
    description: "แพลตฟอร์ม Food Delivery และ Food Tech ชั้นนำ เปิดรับ Software Engineer, Data Engineer และ Product",
    note: "",
  },
  {
    id: "COM-008",
    name: "บริษัท อโกด้า เซอร์วิส จำกัด",
    nameEn: "Agoda Service Co., Ltd.",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทจำกัด",
    country: "สิงคโปร์",
    province: "กรุงเทพมหานคร",
    address: "อาคาร The PARQ ชั้น 30 พระราม 4 คลองเตย กรุงเทพฯ 10110",
    website: "https://careersatagoda.com",
    linkedin: "https://linkedin.com/company/agoda",
    contactName: "คุณ Emily Chen",
    contactEmail: "university@agoda.com",
    contactTel: "02-056-0000",
    status: "ร่วมมือ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 4,
    description: "แพลตฟอร์มท่องเที่ยวออนไลน์ระดับโลก สำนักงานใหญ่สิงคโปร์ ศูนย์เทคโนโลยีที่กรุงเทพฯ เปิดรับ Software Engineer และ Data Science",
    note: "",
  },
  {
    id: "COM-009",
    name: "บริษัท ทรู ดิจิตอล กรุ๊ป จำกัด",
    nameEn: "True Digital Group Co., Ltd.",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "18 ถ.รัชดาภิเษก ห้วยขวาง กรุงเทพฯ 10310",
    website: "https://www.truedigital.com",
    linkedin: "https://linkedin.com/company/true-digital-group",
    contactName: "คุณอรพินท์ ทรงคุณ",
    contactEmail: "internship@truedigital.com",
    contactTel: "02-858-3000",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2026-12-31",
    openPositions: 3,
    description: "กลุ่มธุรกิจดิจิทัลของ True Corporation เน้น Cloud, IoT และ Digital Services",
    note: "",
  },
  {
    id: "COM-010",
    name: "บริษัท ไทย สตีล เคเบิ้ล จำกัด (มหาชน)",
    nameEn: "Thai Steel Cable PCL.",
    industry: "อุตสาหกรรมการผลิต",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "พระนครศรีอยุธยา",
    address: "700/700 หมู่ 6 ต.คลองสวนพลู อ.พระนครศรีอยุธยา 13000",
    website: "https://www.thaisteel.co.th",
    linkedin: "",
    contactName: "คุณสมหมาย ศรีสุข",
    contactEmail: "hr@thaisteel.co.th",
    contactTel: "035-225-100",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2027-03-31",
    openPositions: 2,
    description: "ผู้ผลิตสายเคเบิ้ลรถยนต์ชั้นนำ ส่งออกกว่า 70 ประเทศ เปิดรับวิศวกรรมเครื่องกลและไฟฟ้า",
    note: "",
  },
  {
    id: "COM-011",
    name: "การไฟฟ้าส่วนภูมิภาค (PEA)",
    nameEn: "Provincial Electricity Authority (PEA)",
    industry: "พลังงานและสาธารณูปโภค",
    type: "รัฐวิสาหกิจ",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "200 ถ.งามวงศ์วาน ลาดยาว จตุจักร กรุงเทพฯ 10900",
    website: "https://www.pea.co.th",
    linkedin: "https://linkedin.com/company/provincial-electricity-authority",
    contactName: "คุณวิรัช พลังงาน",
    contactEmail: "intern@pea.co.th",
    contactTel: "02-590-5000",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2027-09-30",
    openPositions: 3,
    description: "รัฐวิสาหกิจด้านพลังงาน เปิดรับวิศวกรรมไฟฟ้าและวิศวกรรมระบบไฟฟ้ากำลัง",
    note: "",
  },
  {
    id: "COM-012",
    name: "บริษัท ฮิตาชิ อีเนอร์ยี (ประเทศไทย) จำกัด",
    nameEn: "Hitachi Energy (Thailand) Co., Ltd.",
    industry: "อิเล็กทรอนิกส์",
    type: "บริษัทจำกัด",
    country: "ญี่ปุ่น",
    province: "ชลบุรี",
    address: "700/456 นิคมอุตสาหกรรมอมตะนคร ชลบุรี 20000",
    website: "https://www.hitachienergy.com",
    linkedin: "https://linkedin.com/company/hitachi-energy",
    contactName: "คุณ Yuki Tanaka",
    contactEmail: "hr.th@hitachienergy.com",
    contactTel: "038-214-100",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2026-06-30",
    openPositions: 2,
    description: "ผู้ผลิตระบบพลังงานและหม้อแปลงไฟฟ้า บริษัทสัญชาติญี่ปุ่น สำนักงานในไทยที่อมตะนคร เปิดรับวิศวกรรมไฟฟ้าและระบบควบคุม",
    note: "",
  },
  {
    id: "COM-013",
    name: "บริษัท มิตซูบิชิ อีเล็คทริค แฟคทอรี่ ออโตเมชั่น (ประเทศไทย) จำกัด",
    nameEn: "Mitsubishi Electric Factory Automation (Thailand) Co., Ltd.",
    industry: "อิเล็กทรอนิกส์",
    type: "บริษัทจำกัด",
    country: "ญี่ปุ่น",
    province: "สมุทรปราการ",
    address: "101 ต.บางพลี อ.บางพลี สมุทรปราการ 10540",
    website: "https://www.mitsubishi-fa.co.th",
    linkedin: "https://linkedin.com/company/mitsubishi-electric",
    contactName: "คุณ Kenji Nakamura",
    contactEmail: "intern@mefathai.co.th",
    contactTel: "02-717-8000",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2027-03-31",
    openPositions: 3,
    description: "ผู้นำด้านระบบออโตเมชั่นและหุ่นยนต์อุตสาหกรรม บริษัทสัญชาติญี่ปุ่น เปิดรับวิศวกรรมไฟฟ้าและเมคคาทรอนิกส์",
    note: "",
  },
  {
    id: "COM-014",
    name: "บริษัท ฮอนด้า ออโตโมบิล (ประเทศไทย) จำกัด",
    nameEn: "Honda Automobile (Thailand) Co., Ltd.",
    industry: "ยานยนต์",
    type: "บริษัทจำกัด",
    country: "ญี่ปุ่น",
    province: "พระนครศรีอยุธยา",
    address: "1 ถ.โรจนะ ต.หัวรอ อ.พระนครศรีอยุธยา 13000",
    website: "https://www.honda.co.th",
    linkedin: "https://linkedin.com/company/honda-automobile-thailand",
    contactName: "คุณกมล วิเศษ",
    contactEmail: "recruitment@honda.co.th",
    contactTel: "035-391-000",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2026-09-30",
    openPositions: 4,
    description: "ผู้ผลิตรถยนต์ Honda ในไทย บริษัทสัญชาติญี่ปุ่น เปิดรับวิศวกรรมเครื่องกล อุตสาหการ และระบบควบคุม",
    note: "",
  },
  {
    id: "COM-015",
    name: "บริษัท กสิกร บิซิเนส-เทคโนโลยี กรุ๊ป จำกัด (KBTG)",
    nameEn: "Kasikorn Business-Technology Group (KBTG)",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "อาคาร KBTG ลาดพร้าว จตุจักร กรุงเทพฯ 10900",
    website: "https://www.kbtg.tech",
    linkedin: "https://linkedin.com/company/kbtg",
    contactName: "คุณพัชรา เทคนิค",
    contactEmail: "internship@kbtg.tech",
    contactTel: "02-470-1234",
    status: "ร่วมมือ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 5,
    description: "บริษัทเทคโนโลยีชั้นนำของกลุ่มธนาคารกสิกรไทย เน้น AI, Cloud และ Software Development",
    note: "",
  },
  {
    id: "COM-016",
    name: "บริษัท ปูนซิเมนต์ไทย จำกัด (มหาชน) (SCG)",
    nameEn: "Siam Cement Group (SCG)",
    industry: "ก่อสร้างและโยธา",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "1 ถ.ปูนซิเมนต์ไทย บางซื่อ กรุงเทพฯ 10800",
    website: "https://www.scg.com",
    linkedin: "https://linkedin.com/company/scg",
    contactName: "คุณรุ่งโรจน์ สยาม",
    contactEmail: "intern@scg.com",
    contactTel: "02-586-3333",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2027-12-31",
    openPositions: 6,
    description: "กลุ่มบริษัทวัสดุก่อสร้างและปิโตรเคมีชั้นนำ เปิดรับหลากหลายสาขาวิศวกรรมและวิทยาศาสตร์",
    note: "",
  },
  {
    id: "COM-017",
    name: "บริษัท บ้านปู จำกัด (มหาชน)",
    nameEn: "Banpu PCL.",
    industry: "พลังงานและสาธารณูปโภค",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "1550 ถ.เพชรบุรีตัดใหม่ มักกะสัน ราชเทวี กรุงเทพฯ 10400",
    website: "https://www.banpu.com",
    linkedin: "https://linkedin.com/company/banpu",
    contactName: "คุณสิรินทร์ พลังงาน",
    contactEmail: "hr@banpu.com",
    contactTel: "02-694-6600",
    status: "รอดำเนินการ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 2,
    description: "บริษัทพลังงานระดับนานาชาติ เน้นถ่านหินและพลังงานสะอาด เปิดรับวิศวกรรมเหมืองแร่และสิ่งแวดล้อม",
    note: "อยู่ระหว่างเจรจา MOU",
  },
  {
    id: "COM-018",
    name: "บริษัท ไออาร์พีซี จำกัด (มหาชน)",
    nameEn: "IRPC PCL.",
    industry: "เคมีและวัสดุ",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "ระยอง",
    address: "299 ถ.สุขุมวิท ต.เชิงเนิน อ.เมือง ระยอง 21000",
    website: "https://www.irpc.co.th",
    linkedin: "https://linkedin.com/company/irpc",
    contactName: "คุณประเสริฐ เคมี",
    contactEmail: "hr@irpc.co.th",
    contactTel: "038-611-000",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2026-03-31",
    openPositions: 2,
    description: "กลุ่มธุรกิจปิโตรเคมีครบวงจร เปิดรับวิศวกรรมเคมีและกระบวนการ",
    note: "",
  },
  {
    id: "COM-019",
    name: "บริษัท อมตะ คอร์ปอเรชัน จำกัด (มหาชน)",
    nameEn: "Amata Corporation PCL.",
    industry: "นิคมอุตสาหกรรม",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "ชลบุรี",
    address: "700/1 ถ.บางนา-ตราด กม.57 อ.เมือง ชลบุรี 20000",
    website: "https://www.amata.com",
    linkedin: "https://linkedin.com/company/amata-corporation",
    contactName: "คุณปราณี นิคม",
    contactEmail: "hr@amata.com",
    contactTel: "038-939-007",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2027-06-30",
    openPositions: 1,
    description: "ผู้พัฒนานิคมอุตสาหกรรมชั้นนำ รองรับอุตสาหกรรม EV และ Smart Industry",
    note: "",
  },
  {
    id: "COM-020",
    name: "บริษัท บ๊อช ออโตโมทีฟ เทคโนโลยี (ประเทศไทย) จำกัด",
    nameEn: "Bosch Automotive Technology (Thailand) Co., Ltd.",
    industry: "ยานยนต์",
    type: "บริษัทจำกัด",
    country: "เยอรมนี",
    province: "ชลบุรี",
    address: "700/458 นิคมอุตสาหกรรมอมตะนคร ชลบุรี 20000",
    website: "https://www.bosch.co.th",
    linkedin: "https://linkedin.com/company/bosch",
    contactName: "คุณ Hans Mueller",
    contactEmail: "intern@bosch.co.th",
    contactTel: "038-215-555",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2027-03-31",
    openPositions: 3,
    description: "ผู้นำด้านชิ้นส่วนยานยนต์และระบบ IoT บริษัทสัญชาติเยอรมัน เปิดรับวิศวกรรมไฟฟ้า เครื่องกล และซอฟต์แวร์",
    note: "",
  },
  {
    id: "COM-021",
    name: "บริษัท ซีเมนส์ (ประเทศไทย) จำกัด",
    nameEn: "Siemens (Thailand) Co., Ltd.",
    industry: "อิเล็กทรอนิกส์",
    type: "บริษัทจำกัด",
    country: "เยอรมนี",
    province: "กรุงเทพมหานคร",
    address: "2/9 ถ.เพลินจิต ลุมพินี ปทุมวัน กรุงเทพฯ 10330",
    website: "https://www.siemens.co.th",
    linkedin: "https://linkedin.com/company/siemens",
    contactName: "คุณ Thomas Weber",
    contactEmail: "careers.th@siemens.com",
    contactTel: "02-255-9700",
    status: "ร่วมมือ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 2,
    description: "บริษัทเทคโนโลยีระดับโลกสัญชาติเยอรมัน เน้น Automation, Digitalization และพลังงาน เปิดรับวิศวกรรมทุกสาขา",
    note: "",
  },
  {
    id: "COM-022",
    name: "บริษัท เจริญโภคภัณฑ์อาหาร จำกัด (มหาชน) (CPF)",
    nameEn: "Charoen Pokphand Foods PCL. (CPF)",
    industry: "อุตสาหกรรมการผลิต",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "313/1 ถ.สีลม บางรัก กรุงเทพฯ 10500",
    website: "https://www.cpfworldwide.com",
    linkedin: "https://linkedin.com/company/cpf-charoen-pokphand-foods",
    contactName: "คุณสุรัตน์ อาหาร",
    contactEmail: "internship@cpf.co.th",
    contactTel: "02-625-8000",
    status: "รอดำเนินการ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 0,
    description: "บริษัทผลิตและแปรรูปอาหารระดับโลก เปิดรับวิศวกรรมอาหาร เครื่องกล และระบบควบคุม",
    note: "อยู่ระหว่างเจรจา",
  },
  {
    id: "COM-023",
    name: "บริษัท ดับบลิวเอชเอ คอร์ปอเรชั่น จำกัด (มหาชน)",
    nameEn: "WHA Corporation PCL.",
    industry: "นิคมอุตสาหกรรม",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "ชลบุรี",
    address: "22 ถ.วิทยุ ลุมพินี ปทุมวัน กรุงเทพฯ 10330",
    website: "https://www.wha-group.com",
    linkedin: "https://linkedin.com/company/wha-corporation",
    contactName: "คุณจิตรลดา นิคม",
    contactEmail: "hr@wha-group.com",
    contactTel: "02-121-6200",
    status: "ร่วมมือ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 1,
    description: "ผู้พัฒนานิคมอุตสาหกรรมและโลจิสติกส์ รองรับ EEC และ Smart City",
    note: "",
  },
  {
    id: "COM-024",
    name: "บริษัท แกรนด์ สตาร์ เทคโนโลยี จำกัด",
    nameEn: "Grand Star Technology Co., Ltd.",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทจำกัด",
    country: "ไทย",
    province: "เชียงใหม่",
    address: "99 ถ.นิมมานเหมินท์ สุเทพ เมือง เชียงใหม่ 50200",
    website: "https://www.grandstar.co.th",
    linkedin: "",
    contactName: "คุณกิตติ ล้านนา",
    contactEmail: "jobs@grandstar.co.th",
    contactTel: "053-215-400",
    status: "รอดำเนินการ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 2,
    description: "บริษัท Software House ในภาคเหนือ เน้น ERP, Mobile App และ Web Development",
    note: "อยู่ระหว่างพิจารณา MOU",
  },
  {
    id: "COM-025",
    name: "บริษัท เนชั่นแนล ไอทีเอ็มเอ็กซ์ จำกัด (NITMX)",
    nameEn: "National ITMX Co., Ltd.",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "ถ.เพชรบุรี ราชเทวี กรุงเทพฯ 10400",
    website: "https://www.nitmx.co.th",
    linkedin: "",
    contactName: "คุณสุวัฒน์ ไอที",
    contactEmail: "hr@nitmx.co.th",
    contactTel: "02-206-9000",
    status: "รอดำเนินการ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 3,
    description: "ผู้ให้บริการโครงสร้างพื้นฐานด้านการชำระเงิน (PromptPay) เปิดรับวิศวกรรมคอมพิวเตอร์และ IT",
    note: "",
  },
  {
    id: "COM-026",
    name: "บริษัท ซีพี ออลล์ จำกัด (มหาชน) — Tech Division",
    nameEn: "CP All PCL. — Tech Division",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "313 ถ.สีลม บางรัก กรุงเทพฯ 10500",
    website: "https://www.cpall.co.th",
    linkedin: "https://linkedin.com/company/cp-all",
    contactName: "คุณนงเยาว์ เทคโนโลยี",
    contactEmail: "tech.intern@cpall.co.th",
    contactTel: "02-677-9000",
    status: "ระงับ",
    mouStatus: "มี MOU",
    mouExpiry: "2025-12-31",
    openPositions: 0,
    description: "ฝ่ายเทคโนโลยีของ 7-Eleven Thailand เน้น Retail Tech และ Data Analytics",
    note: "MOU หมดอายุ อยู่ระหว่างต่ออายุ",
  },
  {
    id: "COM-027",
    name: "บริษัท ไทยยูเนี่ยน กรุ๊ป จำกัด (มหาชน)",
    nameEn: "Thai Union Group PCL.",
    industry: "อุตสาหกรรมการผลิต",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "สมุทรสาคร",
    address: "72/1 ถ.มหาชัย สมุทรสาคร 74000",
    website: "https://www.thaiunion.com",
    linkedin: "https://linkedin.com/company/thai-union-group",
    contactName: "คุณมณีรัตน์ ทะเล",
    contactEmail: "intern@thaiunion.com",
    contactTel: "034-496-000",
    status: "ระงับ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 0,
    description: "ผู้ผลิตอาหารทะเลแปรรูประดับโลก เปิดรับวิศวกรรมอาหารและอุตสาหการ",
    note: "ระงับรับนักศึกษาชั่วคราว",
  },
  {
    id: "COM-028",
    name: "บริษัท พีอีเอ เอ็นคอม อินเตอร์เนชั่นแนล จำกัด",
    nameEn: "PEA ENCOM International Co., Ltd.",
    industry: "พลังงานและสาธารณูปโภค",
    type: "บริษัทจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "200 ถ.งามวงศ์วาน ลาดยาว จตุจักร กรุงเทพฯ 10900",
    website: "https://www.pea-encom.com",
    linkedin: "",
    contactName: "คุณวรพล พลังงาน",
    contactEmail: "hr@pea-encom.com",
    contactTel: "02-590-5100",
    status: "รอดำเนินการ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 1,
    description: "บริษัทลูกของ PEA ด้านพลังงานทดแทนและระบบไฟฟ้าอัจฉริยะ",
    note: "",
  },
  {
    id: "COM-029",
    name: "บริษัท เทเลอินโฟ มีเดีย จำกัด (มหาชน)",
    nameEn: "Teleinfo Media PCL.",
    industry: "เทคโนโลยีสารสนเทศ",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "กรุงเทพมหานคร",
    address: "99/9 ถ.แจ้งวัฒนะ หลักสี่ กรุงเทพฯ 10210",
    website: "https://www.teleinfomedia.co.th",
    linkedin: "",
    contactName: "คุณสุภาพร ดิจิทัล",
    contactEmail: "jobs@teleinfomedia.co.th",
    contactTel: "02-100-9000",
    status: "ระงับ",
    mouStatus: "ไม่มี MOU",
    mouExpiry: "",
    openPositions: 0,
    description: "ผู้ให้บริการข้อมูลและโซลูชั่น Digital Marketing",
    note: "ระงับชั่วคราว รอทิศทางใหม่",
  },
  {
    id: "COM-030",
    name: "บริษัท สหวิริยาสตีลอินดัสตรี จำกัด (มหาชน) (SSI)",
    nameEn: "Sahaviriya Steel Industries PCL. (SSI)",
    industry: "อุตสาหกรรมการผลิต",
    type: "บริษัทมหาชนจำกัด",
    country: "ไทย",
    province: "ประจวบคีรีขันธ์",
    address: "9/1 หมู่ 8 ต.แม่รำพึง อ.บางสะพาน ประจวบคีรีขันธ์ 77140",
    website: "https://www.ssi-steel.com",
    linkedin: "",
    contactName: "คุณอุดม เหล็กกล้า",
    contactEmail: "hr@ssi-steel.com",
    contactTel: "032-619-000",
    status: "ร่วมมือ",
    mouStatus: "มี MOU",
    mouExpiry: "2026-09-30",
    openPositions: 2,
    description: "ผู้ผลิตเหล็กแผ่นรีดร้อนชั้นนำ เปิดรับวิศวกรรมวัสดุและโลหการ เครื่องกล",
    note: "",
  },
];
