export const DEFAULT_JOBS = [
  {
    id: "JOB-001",
    title: "วิศวกรซอฟต์แวร์ฝึกงาน",
    titleEn: "Software Engineering Intern",
    companyLogo: "/logo/companies/toyota.png",
    companyName: "บริษัท โตโยต้า มอเตอร์ ประเทศไทย จำกัด",
    type: "ฝึกงาน",
    field: "วิศวกรรมคอมพิวเตอร์",
    location: "สมุทรปราการ",
    country: "ไทย",
    salary: "15,000 บาท/เดือน",
    duration: "2 เดือน",
    startDate: "2026-08-01",
    deadline: "2026-07-25",
    slots: 3,
    applications: 14,
    status: "เปิดรับ",
    tags: ["Python", "Java", "MES", "SQL"],
    description: "พัฒนาระบบ MES (Manufacturing Execution System) ร่วมกับทีม IT ในสายการผลิต เรียนรู้การทำงานจริงในสภาพแวดล้อมโรงงานอุตสาหกรรม",
    requirements: "กำลังศึกษาสาขาวิศวกรรมคอมพิวเตอร์ ปีที่ 3–4 มีความรู้พื้นฐาน Python หรือ Java สามารถสื่อสารภาษาอังกฤษได้",
    welfare: "ค่าเดินทาง 3,000 บาท/เดือน · ค่าอาหารกลางวัน · ประกันอุบัติเหตุ · มีที่พักสำหรับต่างจังหวัด · Certificate ออกให้โดย Toyota Motor Thailand",
    note: "",
  },
  {
    id: "JOB-002",
    title: "วิศวกรออกแบบเครื่องกล",
    titleEn: "Mechanical Design Engineer",
    companyLogo: "/logo/companies/toyota.png",
    companyName: "บริษัท โตโยต้า มอเตอร์ ประเทศไทย จำกัด",
    type: "งานประจำ",
    field: "วิศวกรรมเครื่องกล",
    location: "สมุทรปราการ",
    country: "ไทย",
    salary: "35,000–50,000 บาท/เดือน",
    duration: "",
    startDate: "2026-08-01",
    deadline: "2026-07-20",
    slots: 2,
    applications: 38,
    status: "เปิดรับ",
    tags: ["CATIA", "SolidWorks", "CAD/CAM", "FEA"],
    description: "ออกแบบและพัฒนาชิ้นส่วนยานยนต์ ใช้โปรแกรม CAD/CAM วิเคราะห์โครงสร้างและทดสอบต้นแบบ ประสานงานกับทีม R&D ญี่ปุ่น",
    requirements: "จบการศึกษาสาขาวิศวกรรมเครื่องกล มีประสบการณ์ด้าน CAD (CATIA, SolidWorks) มีทักษะภาษาอังกฤษและญี่ปุ่นเบื้องต้น",
    welfare: "ประกันสังคม · ประกันสุขภาพกลุ่ม · กองทุนสำรองเลี้ยงชีพ 5% · โบนัสประจำปี 3–5 เดือน · ค่าล่วงเวลา · เบี้ยขยัน · Toyota Saving Plan",
    note: "",
  },
  {
    id: "JOB-003",
    title: "วิศวกรไฟฟ้าฝึกงาน",
    titleEn: "Electrical Engineering Intern",
    companyLogo: "",
    companyName: "บริษัท เดลต้า อีเลคโทรนิคส์ (ประเทศไทย) จำกัด (มหาชน)",
    type: "ฝึกงาน",
    field: "วิศวกรรมไฟฟ้า",
    location: "สมุทรปราการ",
    country: "ไทย",
    salary: "13,000 บาท/เดือน",
    duration: "3 เดือน",
    startDate: "2026-06-16",
    deadline: "2026-06-15",
    slots: 5,
    applications: 29,
    status: "ปิดรับ",
    tags: ["Power Electronics", "ISO/IEC", "QC", "Inverter"],
    description: "ทดสอบและ QC อุปกรณ์ Power Supply และ Inverter ทำงานร่วมกับฝ่ายวิศวกรรมในสายการผลิต เรียนรู้ระบบ ISO/IEC",
    requirements: "กำลังศึกษาสาขาวิศวกรรมไฟฟ้าหรืออิเล็กทรอนิกส์ ปีที่ 2–4 มีความรู้พื้นฐานวงจรไฟฟ้า",
    welfare: "ค่าเดินทาง 2,500 บาท/เดือน · อาหารกลางวันฟรี (โรงอาหารบริษัท) · ประกันอุบัติเหตุ · Certificate และ Letter of Recommendation",
    note: "",
  },
  {
    id: "JOB-004",
    title: "วิศวกรควบคุมคุณภาพ",
    titleEn: "Quality Control Engineer",
    companyLogo: "/logo/companies/honda.webp",
    companyName: "บริษัท ฮอนด้า ออโตโมบิล (ประเทศไทย) จำกัด",
    type: "งานประจำ",
    field: "วิศวกรรมอุตสาหการ",
    location: "อยุธยา",
    country: "ไทย",
    salary: "32,000–45,000 บาท/เดือน",
    duration: "",
    startDate: "2026-09-01",
    deadline: "2026-07-31",
    slots: 3,
    applications: 22,
    status: "เปิดรับ",
    tags: ["SPC", "FMEA", "ISO/TS16949", "Minitab"],
    description: "ควบคุมคุณภาพในสายการผลิตยานยนต์ ตรวจสอบและวิเคราะห์ของเสีย (defect) พัฒนา SOP และ FMEA ร่วมกับทีม QA",
    requirements: "จบการศึกษาสาขาวิศวกรรมอุตสาหการหรือเครื่องกล มีความรู้ด้าน Statistical Process Control (SPC) และ ISO/TS16949",
    welfare: "ประกันสังคม · ประกันสุขภาพ OPD/IPD · กองทุนสำรองเลี้ยงชีพ · โบนัสประจำปี · ค่าที่พักสำหรับต่างจังหวัด · Honda Training Program",
    note: "ต้องผ่านการฝึกอบรม Honda Training Program 3 เดือนแรก",
  },
  {
    id: "JOB-005",
    title: "วิศวกรระบบฝังตัวฝึกงาน",
    titleEn: "Embedded Systems Engineer Intern",
    companyLogo: "",
    companyName: "บริษัท เดนโซ่ (ประเทศไทย) จำกัด",
    type: "ฝึกงาน",
    field: "วิศวกรรมคอมพิวเตอร์",
    location: "ชลบุรี",
    country: "ไทย",
    salary: "15,000 บาท/เดือน",
    duration: "2 เดือน",
    startDate: "2026-08-01",
    deadline: "2026-07-20",
    slots: 4,
    applications: 18,
    status: "เปิดรับ",
    tags: ["C/C++", "ARM Cortex", "STM32", "CAN Bus"],
    description: "พัฒนาและทดสอบ Firmware สำหรับ ECU ยานยนต์ ทำงานกับ Microcontroller (ARM Cortex, STM32) และ CAN Bus Protocol",
    requirements: "กำลังศึกษาสาขาวิศวกรรมคอมพิวเตอร์หรืออิเล็กทรอนิกส์ มีความรู้ภาษา C/C++ และ Embedded C พื้นฐาน",
    welfare: "ค่าเดินทาง 3,000 บาท/เดือน · อาหารกลางวัน (โรงอาหาร DENSO) · ประกันอุบัติเหตุ · เยี่ยมชมโรงงาน DENSO ญี่ปุ่น (โอกาสพิเศษ) · Certificate",
    note: "",
  },
  {
    id: "JOB-006",
    title: "วิศวกรโยธาฝึกงาน",
    titleEn: "Civil Engineering Intern",
    companyLogo: "",
    companyName: "บริษัท อิตาเลียนไทย ดีเวล๊อปเมนต์ จำกัด (มหาชน)",
    type: "ฝึกงาน",
    field: "วิศวกรรมโยธา",
    location: "กรุงเทพฯ",
    country: "ไทย",
    salary: "12,000 บาท/เดือน",
    duration: "2 เดือน",
    startDate: "2026-06-01",
    deadline: "2026-05-15",
    slots: 6,
    applications: 6,
    status: "เต็มแล้ว",
    tags: ["AutoCAD", "SAP2000", "Surveying", "Structural Design"],
    description: "ร่วมทำงานในโครงการก่อสร้างโครงสร้างพื้นฐาน เรียนรู้การสำรวจและออกแบบโครงสร้าง ใช้โปรแกรม AutoCAD และ SAP2000",
    requirements: "กำลังศึกษาสาขาวิศวกรรมโยธา ปีที่ 3–4 มีความรู้พื้นฐานการออกแบบโครงสร้างและ AutoCAD",
    welfare: "ค่าเดินทาง 2,000 บาท/เดือน · ค่าที่พัก (กรณีประจำไซต์ต่างจังหวัด) · ค่าเบี้ยเลี้ยงประจำวัน · ประกันอุบัติเหตุในไซต์งาน · Certificate ITD",
    note: "รับนักศึกษา KOSEN เป็นพิเศษ",
  },
  {
    id: "JOB-007",
    title: "นักวิทยาศาสตร์ข้อมูลฝึกงาน",
    titleEn: "Data Science Intern",
    companyLogo: "/logo/companies/ptt.webp",
    companyName: "บริษัท ปตท. จำกัด (มหาชน)",
    type: "ฝึกงาน",
    field: "วิศวกรรมคอมพิวเตอร์",
    location: "กรุงเทพฯ",
    country: "ไทย",
    salary: "18,000 บาท/เดือน",
    duration: "3 เดือน",
    startDate: "2026-08-15",
    deadline: "2026-07-31",
    slots: 2,
    applications: 41,
    status: "เปิดรับ",
    tags: ["Python", "pandas", "scikit-learn", "Machine Learning", "IoT"],
    description: "วิเคราะห์ข้อมูลจากระบบ IoT ในโรงกลั่น พัฒนาโมเดล Predictive Maintenance ด้วย Machine Learning ทำงานในทีม Digital Transformation",
    requirements: "กำลังศึกษาสาขาวิศวกรรมคอมพิวเตอร์ วิทยาศาสตร์ข้อมูล หรือที่เกี่ยวข้อง มีความรู้ Python, pandas, scikit-learn",
    welfare: "ค่าเดินทาง 4,000 บาท/เดือน · ค่าอาหาร 500 บาท/วัน · ประกันอุบัติเหตุ PTT · ห้องพักในอาคาร PTT Campus · โอกาสต่อยอดเป็นพนักงาน",
    note: "",
  },
  {
    id: "JOB-008",
    title: "วิศวกรกระบวนการผลิต",
    titleEn: "Process Engineer",
    companyLogo: "/logo/companies/ptt.webp",
    companyName: "บริษัท ปตท. จำกัด (มหาชน)",
    type: "งานประจำ",
    field: "วิศวกรรมเคมี",
    location: "ระยอง",
    country: "ไทย",
    salary: "40,000–60,000 บาท/เดือน",
    duration: "",
    startDate: "2026-10-01",
    deadline: "2026-08-15",
    slots: 2,
    applications: 17,
    status: "เปิดรับ",
    tags: ["HYSYS", "ASPEN Plus", "HAZOP", "Process Simulation"],
    description: "วางแผนและควบคุมกระบวนการผลิตในโรงกลั่นน้ำมัน วิเคราะห์ปัญหาและปรับปรุงประสิทธิภาพการผลิต ใช้ซอฟต์แวร์ HYSYS และ ASPEN",
    requirements: "จบการศึกษาสาขาวิศวกรรมเคมีหรือปิโตรเคมี มีความรู้ Process Simulation และ Safety (HAZOP) มีประสบการณ์ 1-2 ปีจะพิจารณาเป็นพิเศษ",
    welfare: "ประกันสังคม · ประกันสุขภาพกลุ่ม (OPD+IPD+ทันตกรรม) · กองทุนสำรองเลี้ยงชีพ 10% · โบนัสประจำปี 4–6 เดือน · PTT Housing Allowance · ค่ากะ",
    note: "",
  },
  {
    id: "JOB-009",
    title: "นักออกแบบอุตสาหกรรมฝึกงาน",
    titleEn: "Industrial Designer Intern",
    companyLogo: "/logo/companies/mitsubishi.svg",
    companyName: "บริษัท มิตซูบิชิ อีเล็คทริค คอนซูมเมอร์ โปรดักส์ (ประเทศไทย) จำกัด",
    type: "ฝึกงาน",
    field: "การออกแบบอุตสาหกรรม",
    location: "ชลบุรี",
    country: "ไทย",
    salary: "13,000 บาท/เดือน",
    duration: "2 เดือน",
    startDate: "2026-06-01",
    deadline: "2026-05-20",
    slots: 2,
    applications: 9,
    status: "ปิดรับ",
    tags: ["Rhinoceros", "Fusion 360", "Adobe XD", "3D Modeling", "Sketching"],
    description: "ออกแบบผลิตภัณฑ์เครื่องใช้ไฟฟ้าและ UI สำหรับแผงควบคุม ทำงานร่วมกับทีม R&D ญี่ปุ่น ใช้ Rhinoceros, Fusion 360 และ Adobe XD",
    requirements: "กำลังศึกษาสาขาการออกแบบอุตสาหกรรมหรือออกแบบผลิตภัณฑ์ มีทักษะ 3D Modeling และ Sketching มี Portfolio",
    welfare: "ค่าเดินทาง 2,500 บาท/เดือน · ค่าอาหาร (โรงอาหาร Mitsubishi) · ประกันอุบัติเหตุ · โอกาสร่วม Design Review กับทีม R&D ญี่ปุ่น · Certificate",
    note: "รอบนี้ปิดรับสมัครแล้ว รอบหน้าจะเปิดรับ เดือน พ.ย. 2026",
  },
  {
    id: "JOB-010",
    title: "วิศวกรระบบอัตโนมัติและหุ่นยนต์",
    titleEn: "Automation & Robotics Engineer",
    companyLogo: "/logo/companies/honda.webp",
    companyName: "บริษัท ฮอนด้า ออโตโมบิล (ประเทศไทย) จำกัด",
    type: "งานประจำ",
    field: "วิศวกรรมเมคคาทรอนิกส์",
    location: "อยุธยา",
    country: "ไทย",
    salary: "38,000–55,000 บาท/เดือน",
    duration: "",
    startDate: "2026-09-01",
    deadline: "2026-08-01",
    slots: 2,
    applications: 26,
    status: "เต็มแล้ว",
    tags: ["PLC", "FANUC", "Mitsubishi PLC", "Robot Programming", "Jig Design"],
    description: "พัฒนาและบำรุงรักษาระบบหุ่นยนต์และสายการผลิตอัตโนมัติ เขียนโปรแกรม PLC (Mitsubishi, FANUC) ออกแบบ Jig และ Fixture",
    requirements: "จบการศึกษาสาขาวิศวกรรมเมคคาทรอนิกส์ ไฟฟ้า หรืออุตสาหการ มีประสบการณ์ PLC Programming และ Robot Programming (Preferred)",
    welfare: "ประกันสังคม · ประกันสุขภาพกลุ่ม OPD/IPD · กองทุนสำรองเลี้ยงชีพ · โบนัสประจำปี 3–5 เดือน · ค่ากะ · Honda Skill-up Training Program",
    note: "",
  },
];
