const RAW_STUDENTS = [
  // ── KOSEN-KMUTT (STU-001 – STU-034) ───────────────────────────────────────
  {
    id: "STU-001", prefix: "นาย", prefixEn: "Mr.",
    name: "กวิน", nameEn: "Kawin",
    lastname: "มณีวรรณ", lastnameEn: "Maneewan",
    nickname: "วิน",
    gender: "ชาย", dob: "2006-02-06",
    nationalId: "0-0011-00023-07-1", passport: "AE2000001",
    country: "ไทย",
    address: "12/5 ซ.ลาดพร้าว 71 แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพฯ 10230",
    tel: "081-234-5678", email: "kawin@student.kosen.ac.th", lineId: "kawin_me",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "วิศวกรรมเครื่องกล", year: "3",
    advisor: "รศ.ดร.สมชาย วิทยาสุข",
    project: "ระบบควบคุมอุณหภูมิอัจฉริยะสำหรับโรงงานอุตสาหกรรม",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-002", prefix: "นางสาว", prefixEn: "Miss",
    name: "ธนัชพร", nameEn: "Thanatchaporn",
    lastname: "สิทธิ์พงศ์", lastnameEn: "Sithiphong",
    nickname: "แนน",
    gender: "หญิง", dob: "2005-05-13",
    nationalId: "0-0048-00106-26-4", passport: "",
    country: "ไทย",
    address: "34 ถ.รัชดาภิเษก แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "082-345-6789", email: "thanatchaporn@student.kosen.ac.th", lineId: "",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมสิ่งแวดล้อม", year: "4",
    advisor: "ผศ.ดร.วีรชัย อาจหาญ",
    project: "ระบบตรวจสอบสุขภาพโครงสร้างอาคารแบบ Real-time",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "-",
    status: "ฝึกงาน", note: "", avatar: null,
  },
  {
    id: "STU-003", prefix: "นาย", prefixEn: "Mr.",
    name: "ปิติ", nameEn: "Piti",
    lastname: "วรนุกูล", lastnameEn: "Woranukul",
    nickname: "ปิ",
    gender: "ชาย", dob: "2007-08-20",
    nationalId: "0-0085-00189-45-7", passport: "",
    country: "ไทย",
    address: "88/3 หมู่ 4 ต.บางแก้ว อ.บางพลี จ.สมุทรปราการ 10540",
    tel: "083-456-7890", email: "piti@student.kosen.ac.th", lineId: "piti_kosen",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมเคมี", year: "2",
    advisor: "รศ.ดร.สิรินทร์ ชีวะสาธน์",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-004", prefix: "นางสาว", prefixEn: "Miss",
    name: "ลลิตภัทร", nameEn: "Lalitphat",
    lastname: "เตชะวงศ์", lastnameEn: "Techawong",
    nickname: "ลิตา",
    gender: "หญิง", dob: "2004-11-27",
    nationalId: "0-0122-00272-64-0", passport: "",
    country: "ไทย",
    address: "22 ซ.อ่อนนุช 46 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "084-567-8901", email: "lalitphat@student.kosen.ac.th", lineId: "",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "เมคคาทรอนิกส์และระบบอัตโนมัติ", year: "5",
    advisor: "รศ.ดร.สมชาย วิทยาสุข",
    project: "ระบบขับเคลื่อนยานยนต์ไฟฟ้าด้วยมอเตอร์ BLDC",
    scholarship: "ทุน จภ.",
    militaryStatus: "-",
    status: "พักการเรียน", note: "ลาพักการเรียนชั่วคราวด้วยเหตุผลส่วนตัว", avatar: null,
  },
  {
    id: "STU-005", prefix: "นาย", prefixEn: "Mr.",
    name: "ภูดิส", nameEn: "Phudis",
    lastname: "คงสกุล", lastnameEn: "Kongsakul",
    nickname: "ภู",
    gender: "ชาย", dob: "2008-02-06",
    nationalId: "0-0159-00355-83-3", passport: "",
    country: "ไทย",
    address: "5/1 ถ.พระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "085-678-9012", email: "phudis@student.kosen.ac.th", lineId: "phu_kosen",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมโยธา", year: "1",
    advisor: "ผศ.ดร.วีรชัย อาจหาญ",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "พ้นสภาพ", note: "", avatar: null,
  },
  {
    id: "STU-006", prefix: "นาย", prefixEn: "Mr.",
    name: "ตรัยรัตน์", nameEn: "Traiyarat",
    lastname: "อ่อนละมัย", lastnameEn: "Onlamai",
    nickname: "ต้น",
    gender: "ชาย", dob: "2007-05-13",
    nationalId: "0-0196-00438-02-6", passport: "RR8172836",
    country: "ไทย",
    address: "67 ถ.เพชรบุรีตัดใหม่ แขวงบางกะปิ เขตห้วยขวาง กรุงเทพฯ 10310",
    tel: "086-789-0123", email: "traiyarat@student.kosen.ac.th", lineId: "ton_kosen",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมชีวเคมี", year: "2",
    advisor: "รศ.ดร.สิรินทร์ ชีวะสาธน์",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-007", prefix: "นางสาว", prefixEn: "Miss",
    name: "อภิชญา", nameEn: "Aphichaya",
    lastname: "ชนะกิจ", lastnameEn: "Chanakij",
    nickname: "แพรว",
    gender: "หญิง", dob: "2006-08-20",
    nationalId: "0-0233-00521-21-9", passport: "",
    country: "ไทย",
    address: "15/8 ซ.นวมินทร์ 42 แขวงคลองกุ่ม เขตบึงกุ่ม กรุงเทพฯ 10230",
    tel: "087-890-1234", email: "aphichaya@student.kosen.ac.th", lineId: "praew_ee",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "วิศวกรรมเครื่องกล", year: "3",
    advisor: "รศ.ดร.สมชาย วิทยาสุข",
    project: "การเพิ่มประสิทธิภาพการแลกเปลี่ยนความร้อนในระบบ HVAC",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-008", prefix: "นาย", prefixEn: "Mr.",
    name: "นิธิภัทร", nameEn: "Nithiphat",
    lastname: "รัตนวิจิตร", lastnameEn: "Rattanawichit",
    nickname: "นิ",
    gender: "ชาย", dob: "2004-11-27",
    nationalId: "", passport: "XF1641970",
    country: "ญี่ปุ่น",
    address: "4-5-6 Shibuya, Shibuya-ku, Tokyo 150-0002",
    tel: "088-901-2345", email: "nithiphat@student.kosen.ac.th", lineId: "",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมสิ่งแวดล้อม", year: "5",
    advisor: "ผศ.ดร.วีรชัย อาจหาญ",
    project: "การวิเคราะห์เสถียรภาพของโครงสร้างสะพานด้วย Finite Element Method",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่านการเกณฑ์",
    status: "ฝึกงาน", note: "ฝึกงานที่บริษัท Toyota Motor Thailand", avatar: null,
  },
  {
    id: "STU-009", prefix: "นางสาว", prefixEn: "Miss",
    name: "วริษฐา", nameEn: "Warittha",
    lastname: "สุขเกษม", lastnameEn: "Sukkasem",
    nickname: "วา",
    gender: "หญิง", dob: "2005-02-06",
    nationalId: "0-0307-00687-59-4", passport: "",
    country: "ไทย",
    address: "9 ซ.สุขุมวิท 77 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "089-012-3456", email: "warittha@student.kosen.ac.th", lineId: "wa_id",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมเคมี", year: "4",
    advisor: "รศ.ดร.สิรินทร์ ชีวะสาธน์",
    project: "กระบวนการผลิตไบโอดีเซลจากสาหร่ายน้ำจืดด้วยเอนไซม์ Lipase",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-010", prefix: "นาย", prefixEn: "Mr.",
    name: "ชยุต", nameEn: "Chayut",
    lastname: "พรหมเสน", lastnameEn: "Phromsen",
    nickname: "ยุต",
    gender: "ชาย", dob: "2008-05-13",
    nationalId: "1-0344-00770-78-7", passport: "",
    country: "ไทย",
    address: "45/2 หมู่ 7 ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี 12120",
    tel: "090-123-4567", email: "chayut@student.kosen.ac.th", lineId: "chayut_cs",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "เมคคาทรอนิกส์และระบบอัตโนมัติ", year: "1",
    advisor: "รศ.ดร.สมชาย วิทยาสุข",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-011", prefix: "นางสาว", prefixEn: "Miss",
    name: "พิชามญชุ์", nameEn: "Pichamun",
    lastname: "เมธาพันธ์", lastnameEn: "Methaphan",
    nickname: "มิ้น",
    gender: "หญิง", dob: "2007-08-20",
    nationalId: "1-0381-00853-97-0", passport: "GC5345671",
    country: "ไทย",
    address: "78 ถ.พหลโยธิน แขวงพญาไท เขตพญาไท กรุงเทพฯ 10400",
    tel: "091-234-5678", email: "pichamun@student.kosen.ac.th", lineId: "",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมโยธา", year: "2",
    advisor: "ผศ.ดร.วีรชัย อาจหาญ",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-012", prefix: "นาย", prefixEn: "Mr.",
    name: "กษิดิศ", nameEn: "Kasidis",
    lastname: "ศิลาธร", lastnameEn: "Silathorn",
    nickname: "ดิศ",
    gender: "ชาย", dob: "2006-11-27",
    nationalId: "1-0418-00936-16-3", passport: "",
    country: "ไทย",
    address: "33 ซ.จรัญสนิทวงศ์ 13 แขวงบางอ้อ เขตบางพลัด กรุงเทพฯ 10700",
    tel: "092-345-6789", email: "kasidis@student.kosen.ac.th", lineId: "kasi_me",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "เมคคาทรอนิกส์และระบบอัตโนมัติ", year: "3",
    advisor: "รศ.ดร.เกรียงไกร ลักษณ์โกเศศ",
    project: "การออกแบบและพัฒนาหุ่นยนต์เดินสองขาแบบ Bipedal",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-013", prefix: "นางสาว", prefixEn: "Miss",
    name: "นภัสวรรณ", nameEn: "Naphasuwan",
    lastname: "เจริญกิจ", lastnameEn: "Charoenkij",
    nickname: "ฝน",
    gender: "หญิง", dob: "2008-02-06",
    nationalId: "1-0455-01019-35-6", passport: "",
    country: "ไทย",
    address: "101 ถ.นิมมานเหมินท์ ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200",
    tel: "093-456-7890", email: "naphasuwan@student.kosen.ac.th", lineId: "fon_design",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมเคมี", year: "1",
    advisor: "รศ.ดร.อุษา แสงวิเชียร",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-014", prefix: "นาย", prefixEn: "Mr.",
    name: "วรากร", nameEn: "Warakorn",
    lastname: "บุญชูศรี", lastnameEn: "Bunchusri",
    nickname: "กร",
    gender: "ชาย", dob: "2005-05-13",
    nationalId: "1-0492-01102-54-9", passport: "",
    country: "ไทย",
    address: "55/4 หมู่ 2 ต.เชิงดอย อ.ดอยสะเก็ด จ.เชียงใหม่ 50220",
    tel: "094-567-8901", email: "warakorn@student.kosen.ac.th", lineId: "",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมสิ่งแวดล้อม", year: "4",
    advisor: "ผศ.ดร.วีรชัย อาจหาญ",
    project: "การออกแบบระบบระบายน้ำเพื่อรองรับฝนสูงสุดในพื้นที่เมือง",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-015", prefix: "นางสาว", prefixEn: "Miss",
    name: "นลินทิพย์", nameEn: "Nalinttip",
    lastname: "แก้วปัญญา", lastnameEn: "Kaewpanya",
    nickname: "ลิน",
    gender: "หญิง", dob: "2004-08-20",
    nationalId: "1-0529-01185-73-2", passport: "",
    country: "ไทย",
    address: "8/9 ถ.กาญจนวนิช ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา 90110",
    tel: "095-678-9012", email: "nalinttip@student.kosen.ac.th", lineId: "lin_ee",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "วิศวกรรมเครื่องกล", year: "5",
    advisor: "รศ.ดร.เกรียงไกร ลักษณ์โกเศศ",
    project: "ระบบควบคุมอุณหภูมิอัจฉริยะสำหรับโรงงานอุตสาหกรรม",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "ฝึกงาน", note: "ฝึกงานที่บริษัท Thai Steel Cable", avatar: null,
  },
  {
    id: "STU-016", prefix: "นาย", prefixEn: "Mr.",
    name: "ธัชพงศ์", nameEn: "Thatchaphong",
    lastname: "วิชัยดิษฐ", lastnameEn: "Wichaidis",
    nickname: "ธัช",
    gender: "ชาย", dob: "2007-11-27",
    nationalId: "1-0566-01268-92-5", passport: "XP2518506",
    country: "ไทย",
    address: "29 ถ.เจริญกรุง แขวงสี่พระยา เขตบางรัก กรุงเทพฯ 10500",
    tel: "096-789-0123", email: "thatchaphong@student.kosen.ac.th", lineId: "thatch_me",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมสิ่งแวดล้อม", year: "2",
    advisor: "รศ.ดร.ประภาส จงสถิตย์วัฒนา",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-017", prefix: "นางสาว", prefixEn: "Miss",
    name: "ชนิตา", nameEn: "Chanita",
    lastname: "ทองแสนคำ", lastnameEn: "Thongsankham",
    nickname: "ชิ",
    gender: "หญิง", dob: "2006-02-06",
    nationalId: "1-0603-01351-11-8", passport: "",
    country: "ไทย",
    address: "11 ถ.สุขสวัสดิ์ แขวงราษฎร์บูรณะ เขตราษฎร์บูรณะ กรุงเทพฯ 10140",
    tel: "097-890-1234", email: "chanita@student.kosen.ac.th", lineId: "",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมเคมี", year: "3",
    advisor: "ผศ.ดร.ธีรพงศ์ ลิมป์สุทธิ",
    project: "การเพิ่มผลผลิตเอทานอลจากชานอ้อยด้วยยีสต์ที่ดัดแปลงพันธุกรรม",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-018", prefix: "นาย", prefixEn: "Mr.",
    name: "ปัณณรัตน์", nameEn: "Pannarat",
    lastname: "โกมลวิช", lastnameEn: "Komonwit",
    nickname: "ปัณ",
    gender: "ชาย", dob: "2004-05-13",
    nationalId: "1-0640-01434-30-1", passport: "",
    country: "ไทย",
    address: "63 ถ.ราชพฤกษ์ ต.บางรักพัฒนา อ.บางบัวทอง จ.นนทบุรี 11110",
    tel: "098-901-2345", email: "pannarat@student.kosen.ac.th", lineId: "pan_cs",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "เมคคาทรอนิกส์และระบบอัตโนมัติ", year: "5",
    advisor: "รศ.ดร.เกรียงไกร ลักษณ์โกเศศ",
    project: "ระบบขับเคลื่อนยานยนต์ไฟฟ้าด้วยมอเตอร์ BLDC",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่านการเกณฑ์",
    status: "ฝึกงาน", note: "", avatar: null,
  },
  {
    id: "STU-019", prefix: "นางสาว", prefixEn: "Miss",
    name: "กัญจน์ณัฏฐ์", nameEn: "Kanjanat",
    lastname: "สร้อยมาลา", lastnameEn: "Soimala",
    nickname: "เนย",
    gender: "หญิง", dob: "2008-08-20",
    nationalId: "1-0677-01517-49-3", passport: "",
    country: "ไทย",
    address: "22/5 ซ.บางนา-ตราด 40 แขวงบางนา เขตบางนา กรุงเทพฯ 10260",
    tel: "099-012-3456", email: "kanjanat@student.kosen.ac.th", lineId: "noey_ee",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมโยธา", year: "1",
    advisor: "รศ.ดร.ประภาส จงสถิตย์วัฒนา",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-020", prefix: "นาย", prefixEn: "Mr.",
    name: "ศุภวิชญ์", nameEn: "Suphawit",
    lastname: "อินทรีวงศ์", lastnameEn: "Intreewong",
    nickname: "เก่ง",
    gender: "ชาย", dob: "2005-11-27",
    nationalId: "", passport: "KT7456774",
    country: "ญี่ปุ่น",
    address: "4-5-6 Shibuya, Shibuya-ku, Tokyo 150-0002",
    tel: "081-111-2222", email: "suphawit@student.kosen.ac.th", lineId: "",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมชีวเคมี", year: "4",
    advisor: "ผศ.ดร.ธีรพงศ์ ลิมป์สุทธิ",
    project: "กระบวนการ CO₂ Capture ด้วยตัวดูดซับเอมีนแบบ Solid",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-021", prefix: "นางสาว", prefixEn: "Miss",
    name: "พิมนิภา", nameEn: "Pimnipa",
    lastname: "เพชรนาวา", lastnameEn: "Phetnawa",
    nickname: "พิม",
    gender: "หญิง", dob: "2006-02-06",
    nationalId: "2-0751-01683-87-9", passport: "NA8691341",
    country: "ไทย",
    address: "12/5 ซ.ลาดพร้าว 71 แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพฯ 10230",
    tel: "082-222-3333", email: "pimnipa@student.kosen.ac.th", lineId: "pim_cs",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "วิศวกรรมเครื่องกล", year: "3",
    advisor: "รศ.ดร.เกรียงไกร ลักษณ์โกเศศ",
    project: "การเพิ่มประสิทธิภาพการแลกเปลี่ยนความร้อนในระบบ HVAC",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-022", prefix: "นาย", prefixEn: "Mr.",
    name: "เจตน์สฤษฎิ์", nameEn: "Jetsarit",
    lastname: "โพธิ์ชัยยะ", lastnameEn: "Phochaiya",
    nickname: "เจต",
    gender: "ชาย", dob: "2007-05-13",
    nationalId: "2-0788-01766-06-2", passport: "",
    country: "ไทย",
    address: "34 ถ.รัชดาภิเษก แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "083-333-4444", email: "jetsarit@student.kosen.ac.th", lineId: "jet_ee",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมสิ่งแวดล้อม", year: "2",
    advisor: "รศ.ดร.ประภาส จงสถิตย์วัฒนา",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-023", prefix: "นางสาว", prefixEn: "Miss",
    name: "วรัทยา", nameEn: "Warataya",
    lastname: "ยอดยิ้ม", lastnameEn: "Yodyim",
    nickname: "วาว",
    gender: "หญิง", dob: "2004-08-20",
    nationalId: "2-0825-01849-25-5", passport: "",
    country: "ไทย",
    address: "88/3 หมู่ 4 ต.บางแก้ว อ.บางพลี จ.สมุทรปราการ 10540",
    tel: "084-444-5555", email: "warataya@student.kosen.ac.th", lineId: "",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมเคมี", year: "5",
    advisor: "ผศ.ดร.ธีรพงศ์ ลิมป์สุทธิ",
    project: "กระบวนการผลิตไบโอดีเซลจากสาหร่ายน้ำจืดด้วยเอนไซม์ Lipase",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-024", prefix: "นาย", prefixEn: "Mr.",
    name: "ธีรภัทร", nameEn: "Thiraphat",
    lastname: "คำเงิน", lastnameEn: "Khamngoen",
    nickname: "เปา",
    gender: "ชาย", dob: "2008-11-27",
    nationalId: "2-0862-01932-44-8", passport: "",
    country: "ไทย",
    address: "22 ซ.อ่อนนุช 46 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "085-555-6666", email: "thiraphat@student.kosen.ac.th", lineId: "pao_me",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "เมคคาทรอนิกส์และระบบอัตโนมัติ", year: "1",
    advisor: "รศ.ดร.เกรียงไกร ลักษณ์โกเศศ",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-025", prefix: "นางสาว", prefixEn: "Miss",
    name: "สิรินทร์", nameEn: "Sirin",
    lastname: "บุษราคัม", lastnameEn: "Butsarakham",
    nickname: "ทิพย์",
    gender: "หญิง", dob: "2005-02-06",
    nationalId: "2-0899-02015-63-1", passport: "",
    country: "ไทย",
    address: "5/1 ถ.พระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "086-666-7777", email: "sirin@student.kosen.ac.th", lineId: "tip_cs",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมโยธา", year: "4",
    advisor: "รศ.ดร.ประภาส จงสถิตย์วัฒนา",
    project: "การประเมินความเสี่ยงน้ำท่วมในพื้นที่กรุงเทพมหานครด้วย GIS",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-026", prefix: "นาย", prefixEn: "Mr.",
    name: "ณภัทรดนัย", nameEn: "Naphatdanai",
    lastname: "หิรัญพานิช", lastnameEn: "Hiranphanit",
    nickname: "นน",
    gender: "ชาย", dob: "2006-05-13",
    nationalId: "2-0936-02098-82-4", passport: "DM5864176",
    country: "ไทย",
    address: "67 ถ.เพชรบุรีตัดใหม่ แขวงบางกะปิ เขตห้วยขวาง กรุงเทพฯ 10310",
    tel: "087-777-8888", email: "naphatdanai@student.kosen.ac.th", lineId: "",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมชีวเคมี", year: "3",
    advisor: "ผศ.ดร.ธีรพงศ์ ลิมป์สุทธิ",
    project: "การพัฒนา Biosensor ตรวจวัดสารปนเปื้อนหนักในน้ำ",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-027", prefix: "นางสาว", prefixEn: "Miss",
    name: "อาภาภัทร", nameEn: "Arpaphat",
    lastname: "เทพนิยม", lastnameEn: "Thepniyom",
    nickname: "อ้อ",
    gender: "หญิง", dob: "2007-08-20",
    nationalId: "2-0973-02181-01-7", passport: "",
    country: "ไทย",
    address: "15/8 ซ.นวมินทร์ 42 แขวงคลองกุ่ม เขตบึงกุ่ม กรุงเทพฯ 10230",
    tel: "088-888-9999", email: "arpaphat@student.kosen.ac.th", lineId: "ao_design",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "วิศวกรรมเครื่องกล", year: "2",
    advisor: "รศ.ดร.เกรียงไกร ลักษณ์โกเศศ",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-028", prefix: "นาย", prefixEn: "Mr.",
    name: "สิทธินนท์", nameEn: "Sithinon",
    lastname: "มีสุวรรณ", lastnameEn: "Meesuwan",
    nickname: "โชค",
    gender: "ชาย", dob: "2004-11-27",
    nationalId: "2-1010-02264-20-1", passport: "",
    country: "ไทย",
    address: "200 ถ.ศรีนครินทร์ แขวงหนองบอน เขตประเวศ กรุงเทพฯ 10250",
    tel: "089-999-0000", email: "sithinon@student.kosen.ac.th", lineId: "chok_cs",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมสิ่งแวดล้อม", year: "5",
    advisor: "รศ.ดร.ประภาส จงสถิตย์วัฒนา",
    project: "การออกแบบระบบระบายน้ำเพื่อรองรับฝนสูงสุดในพื้นที่เมือง",
    scholarship: "ทุน จภ.",
    militaryStatus: "ได้รับการยกเว้น",
    status: "ฝึกงาน", note: "ฝึกงานที่บริษัท Italian-Thai Development", avatar: null,
  },
  {
    id: "STU-029", prefix: "นางสาว", prefixEn: "Miss",
    name: "พัชราภา", nameEn: "Patcharapha",
    lastname: "เฟื่องฟู", lastnameEn: "Fueangfu",
    nickname: "แป้ง",
    gender: "หญิง", dob: "2008-02-06",
    nationalId: "2-1047-02347-39-3", passport: "",
    country: "ไทย",
    address: "9 ซ.สุขุมวิท 77 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "090-000-1111", email: "patcharapha@student.kosen.ac.th", lineId: "",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมเคมี", year: "1",
    advisor: "ผศ.ดร.ธีรพงศ์ ลิมป์สุทธิ",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-030", prefix: "นาย", prefixEn: "Mr.",
    name: "รัชพล", nameEn: "Rachaphon",
    lastname: "นาคบรรพต", lastnameEn: "Nakbunphot",
    nickname: "รัช",
    gender: "ชาย", dob: "2005-05-13",
    nationalId: "3-1084-02430-58-6", passport: "",
    country: "ไทย",
    address: "45/2 หมู่ 7 ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี 12120",
    tel: "091-111-3333", email: "rachaphon@student.kosen.ac.th", lineId: "rach_ee",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "เมคคาทรอนิกส์และระบบอัตโนมัติ", year: "4",
    advisor: "รศ.ดร.เกรียงไกร ลักษณ์โกเศศ",
    project: "การออกแบบแขนกลสำหรับงานประกอบชิ้นส่วนอิเล็กทรอนิกส์",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-031", prefix: "นางสาว", prefixEn: "Miss",
    name: "สกาวฟ้า", nameEn: "Sakaofa",
    lastname: "พันธุ์ประดิษฐ์", lastnameEn: "Phanpradit",
    nickname: "เดือน",
    gender: "หญิง", dob: "2006-08-20",
    nationalId: "3-1121-02513-77-9", passport: "UY3037011",
    country: "ไทย",
    address: "78 ถ.พหลโยธิน แขวงพญาไท เขตพญาไท กรุงเทพฯ 10400",
    tel: "092-222-4444", email: "sakaofa@student.kosen.ac.th", lineId: "duean_design",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมโยธา", year: "3",
    advisor: "รศ.ดร.ประภาส จงสถิตย์วัฒนา",
    project: "การบำบัดน้ำเสียจากโรงงานอุตสาหกรรมด้วยระบบ Constructed Wetland",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-032", prefix: "นาย", prefixEn: "Mr.",
    name: "กฤตภัค", nameEn: "Kritphak",
    lastname: "ทวีธนกุล", lastnameEn: "Thaweethanakun",
    nickname: "กฤต",
    gender: "ชาย", dob: "2007-11-27",
    nationalId: "3-1158-02596-96-2", passport: "",
    country: "ไทย",
    address: "33 ซ.จรัญสนิทวงศ์ 13 แขวงบางอ้อ เขตบางพลัด กรุงเทพฯ 10700",
    tel: "093-333-5555", email: "kritphak@student.kosen.ac.th", lineId: "krit_cs",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเคมีและชีวเคมี",
    department: "วิศวกรรมเคมี", major: "วิศวกรรมชีวเคมี", year: "2",
    advisor: "ผศ.ดร.ธีรพงศ์ ลิมป์สุทธิ",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-033", prefix: "นางสาว", prefixEn: "Miss",
    name: "ฟ้าพราว", nameEn: "Fapraw",
    lastname: "ใจภักดิ์", lastnameEn: "Jaiphak",
    nickname: "ฟ้า",
    gender: "หญิง", dob: "2004-02-06",
    nationalId: "3-1195-02679-15-5", passport: "",
    country: "ไทย",
    address: "101 ถ.นิมมานเหมินท์ ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200",
    tel: "094-444-6666", email: "fapraw@student.kosen.ac.th", lineId: "",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมเครื่องกล",
    department: "วิศวกรรมเครื่องกล", major: "วิศวกรรมเครื่องกล", year: "5",
    advisor: "รศ.ดร.เกรียงไกร ลักษณ์โกเศศ",
    project: "การออกแบบและพัฒนาหุ่นยนต์เดินสองขาแบบ Bipedal",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "พักการเรียน", note: "ลาพักเพื่อดูแลครอบครัว", avatar: null,
  },
  {
    id: "STU-034", prefix: "นาย", prefixEn: "Mr.",
    name: "ปรัชญ์", nameEn: "Prach",
    lastname: "มณีวงศ์", lastnameEn: "Maneewong",
    nickname: "ปรัช",
    gender: "ชาย", dob: "2005-05-13",
    nationalId: "3-1232-02762-34-8", passport: "",
    country: "ไทย",
    address: "55/4 หมู่ 2 ต.เชิงดอย อ.ดอยสะเก็ด จ.เชียงใหม่ 50220",
    tel: "095-555-7777", email: "prach@student.kosen.ac.th", lineId: "prach_me",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-KMUTT", faculty: "วิศวกรรมโยธา",
    department: "วิศวกรรมโยธา", major: "วิศวกรรมสิ่งแวดล้อม", year: "4",
    advisor: "รศ.ดร.ประภาส จงสถิตย์วัฒนา",
    project: "ระบบบริหารจัดการน้ำอัจฉริยะสำหรับชุมชนเมือง",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },

  // ── KOSEN-KMITL (STU-035 – STU-067) ──────────────────────────────────────
  {
    id: "STU-035", prefix: "นางสาว", prefixEn: "Miss",
    name: "นิชาภัทร", nameEn: "Nichaphat",
    lastname: "สุขพาณิชย์", lastnameEn: "Sukhphanit",
    nickname: "นิชา",
    gender: "หญิง", dob: "2008-08-20",
    nationalId: "3-1269-02845-53-1", passport: "",
    country: "ไทย",
    address: "8/9 ถ.กาญจนวนิช ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา 90110",
    tel: "096-666-8888", email: "nichaphat@student.kosen.ac.th", lineId: "nicha_cs",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "วิศวกรรมไฟฟ้ากำลัง", year: "1",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-036", prefix: "นาย", prefixEn: "Mr.",
    name: "อิทธิภัทร", nameEn: "Ittiphat",
    lastname: "สว่างนิตย์", lastnameEn: "Sawangnit",
    nickname: "อิท",
    gender: "ชาย", dob: "2006-11-27",
    nationalId: "", passport: "KK9209846",
    country: "ญี่ปุ่น",
    address: "7-8 Umeda, Kita-ku, Osaka 530-0001",
    tel: "097-777-9999", email: "ittiphat@student.kosen.ac.th", lineId: "",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมโทรคมนาคม", year: "3",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "ระบบสื่อสารไร้สายความหน่วงต่ำสำหรับ Industrial IoT บน FPGA",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-037", prefix: "นางสาว", prefixEn: "Miss",
    name: "ลักษิกา", nameEn: "Laksika",
    lastname: "เรืองศักดิ์", lastnameEn: "Rueangsak",
    nickname: "แนน",
    gender: "หญิง", dob: "2005-02-06",
    nationalId: "3-1343-03011-91-7", passport: "",
    country: "ไทย",
    address: "11 ถ.สุขสวัสดิ์ แขวงราษฎร์บูรณะ เขตราษฎร์บูรณะ กรุงเทพฯ 10140",
    tel: "098-888-0000", email: "laksika@student.kosen.ac.th", lineId: "nan_design",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "วิศวกรรมคอมพิวเตอร์", year: "4",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "การเร่งความเร็ว Transformer Inference บน Custom RISC-V Processor",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "ฝึกงาน", note: "", avatar: null,
  },
  {
    id: "STU-038", prefix: "นาย", prefixEn: "Mr.",
    name: "ธิติกร", nameEn: "Thitikorn",
    lastname: "วัฒนประดิษฐ์", lastnameEn: "Watthanapradit",
    nickname: "ธิ",
    gender: "ชาย", dob: "2004-05-13",
    nationalId: "3-1380-03094-10-0", passport: "",
    country: "ไทย",
    address: "63 ถ.ราชพฤกษ์ ต.บางรักพัฒนา อ.บางบัวทอง จ.นนทบุรี 11110",
    tel: "099-999-1111", email: "thitikorn@student.kosen.ac.th", lineId: "thi_cs",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "ระบบควบคุมอัตโนมัติ", year: "5",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "ตัวแปลงไฟฟ้า DC-DC แบบ Bidirectional สำหรับระบบพลังงาน Solar",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่านการเกณฑ์",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-039", prefix: "นางสาว", prefixEn: "Miss",
    name: "จิรัชยา", nameEn: "Jirachaya",
    lastname: "ดำรงเดช", lastnameEn: "Damrongdej",
    nickname: "จิ",
    gender: "หญิง", dob: "2007-08-20",
    nationalId: "3-1417-03177-29-2", passport: "",
    country: "ไทย",
    address: "22/5 ซ.บางนา-ตราด 40 แขวงบางนา เขตบางนา กรุงเทพฯ 10260",
    tel: "081-121-2121", email: "jirachaya@student.kosen.ac.th", lineId: "",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมอิเล็กทรอนิกส์", year: "2",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-040", prefix: "นาย", prefixEn: "Mr.",
    name: "ยศภัทร", nameEn: "Yotphat",
    lastname: "ลิ้มพาณิช", lastnameEn: "Limphanit",
    nickname: "ยศ",
    gender: "ชาย", dob: "2008-11-27",
    nationalId: "4-1454-03260-48-5", passport: "",
    country: "ไทย",
    address: "148 ถ.ขอนแก่น-อุดรธานี ต.ในเมือง อ.เมือง จ.ขอนแก่น 40000",
    tel: "082-232-3232", email: "yotphat@student.kosen.ac.th", lineId: "yot_ee",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "ปัญญาประดิษฐ์และการเรียนรู้ของเครื่อง", year: "1",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-041", prefix: "นางสาว", prefixEn: "Miss",
    name: "อภิสมา", nameEn: "Aphisama",
    lastname: "ใจเกษม", lastnameEn: "Jaikasem",
    nickname: "อะ",
    gender: "หญิง", dob: "2004-02-06",
    nationalId: "4-1491-03343-67-8", passport: "AW6382681",
    country: "ไทย",
    address: "12/5 ซ.ลาดพร้าว 71 แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพฯ 10230",
    tel: "083-343-4343", email: "aphisama@student.kosen.ac.th", lineId: "a_design",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "วิศวกรรมไฟฟ้ากำลัง", year: "5",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "ระบบควบคุมมอเตอร์ Induction แบบ Field Oriented Control",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-042", prefix: "นาย", prefixEn: "Mr.",
    name: "ชัชวิน", nameEn: "Chatchawin",
    lastname: "ก้าวรุ่งเรือง", lastnameEn: "Kawrungruang",
    nickname: "ชัช",
    gender: "ชาย", dob: "2006-05-13",
    nationalId: "4-1528-03426-86-1", passport: "",
    country: "ไทย",
    address: "34 ถ.รัชดาภิเษก แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "084-454-5454", email: "chatchawin@student.kosen.ac.th", lineId: "",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมโทรคมนาคม", year: "3",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "การออกแบบ Low-Noise Amplifier สำหรับ Satellite Communication",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-043", prefix: "นางสาว", prefixEn: "Miss",
    name: "ประภาสิริ", nameEn: "Praphasiri",
    lastname: "เดชวงศ์ษา", lastnameEn: "Dejwongsa",
    nickname: "ภาวี",
    gender: "หญิง", dob: "2005-08-20",
    nationalId: "4-1565-03509-05-4", passport: "",
    country: "ไทย",
    address: "88/3 หมู่ 4 ต.บางแก้ว อ.บางพลี จ.สมุทรปราการ 10540",
    tel: "085-565-6565", email: "praphasiri@student.kosen.ac.th", lineId: "phawi_me",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "วิศวกรรมคอมพิวเตอร์", year: "4",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "ระบบตรวจจับการบุกรุกเครือข่ายด้วย Graph Neural Network",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-044", prefix: "นาย", prefixEn: "Mr.",
    name: "นัทธพัชร", nameEn: "Nattaphatch",
    lastname: "สุทธิรัตน์วงศ์", lastnameEn: "Suthiratwong",
    nickname: "นัท",
    gender: "ชาย", dob: "2007-11-27",
    nationalId: "4-1602-03592-24-7", passport: "",
    country: "ไทย",
    address: "22 ซ.อ่อนนุช 46 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "086-676-7676", email: "nattaphatch@student.kosen.ac.th", lineId: "nat_ee",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "ระบบควบคุมอัตโนมัติ", year: "2",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-045", prefix: "นางสาว", prefixEn: "Miss",
    name: "เบญจพร", nameEn: "Benjaphorn",
    lastname: "แสงพิทักษ์", lastnameEn: "Sangphitak",
    nickname: "เบญ",
    gender: "หญิง", dob: "2008-02-06",
    nationalId: "4-1639-03675-43-0", passport: "",
    country: "ไทย",
    address: "5/1 ถ.พระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "087-787-8787", email: "benjaphorn@student.kosen.ac.th", lineId: "",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมอิเล็กทรอนิกส์", year: "1",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-046", prefix: "นาย", prefixEn: "Mr.",
    name: "วุฒิพงศ์", nameEn: "Wuttiphong",
    lastname: "ปัองป้อง", lastnameEn: "Pangpong",
    nickname: "วุฒิ",
    gender: "ชาย", dob: "2005-05-13",
    nationalId: "4-1676-03758-62-3", passport: "RH3555516",
    country: "ไทย",
    address: "67 ถ.เพชรบุรีตัดใหม่ แขวงบางกะปิ เขตห้วยขวาง กรุงเทพฯ 10310",
    tel: "088-898-9898", email: "wuttiphong@student.kosen.ac.th", lineId: "wut_cs",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "ปัญญาประดิษฐ์และการเรียนรู้ของเครื่อง", year: "4",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "การออกแบบ Hardware Accelerator สำหรับ Cryptography บน FPGA",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "ฝึกงาน", note: "ฝึกงานที่ NECTEC", avatar: null,
  },
  {
    id: "STU-047", prefix: "นางสาว", prefixEn: "Miss",
    name: "ธมลนันท์", nameEn: "Thamonnan",
    lastname: "คงคาใส", lastnameEn: "Khongkhasai",
    nickname: "มล",
    gender: "หญิง", dob: "2006-08-20",
    nationalId: "4-1713-03841-81-6", passport: "",
    country: "ไทย",
    address: "15/8 ซ.นวมินทร์ 42 แขวงคลองกุ่ม เขตบึงกุ่ม กรุงเทพฯ 10230",
    tel: "089-909-0909", email: "thamonnan@student.kosen.ac.th", lineId: "mon_me",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "วิศวกรรมไฟฟ้ากำลัง", year: "3",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "การพัฒนา MPPT Controller สำหรับแผงโซลาร์เซลล์แบบ Adaptive",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-048", prefix: "นาย", prefixEn: "Mr.",
    name: "สุริยพงศ์", nameEn: "Suriyaphong",
    lastname: "แสงดาวเรือง", lastnameEn: "Saengdaowruang",
    nickname: "ริว",
    gender: "ชาย", dob: "2004-11-27",
    nationalId: "4-1750-03924-00-9", passport: "",
    country: "ไทย",
    address: "200 ถ.ศรีนครินทร์ แขวงหนองบอน เขตประเวศ กรุงเทพฯ 10250",
    tel: "090-010-1010", email: "suriyaphong@student.kosen.ac.th", lineId: "",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมโทรคมนาคม", year: "5",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "ระบบ Beamforming Antenna Array สำหรับการสื่อสาร mmWave",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่านการเกณฑ์",
    status: "ฝึกงาน", note: "ฝึกงานที่ Delta Electronics Thailand", avatar: null,
  },
  {
    id: "STU-049", prefix: "นางสาว", prefixEn: "Miss",
    name: "ขวัญจิรา", nameEn: "Khwanjira",
    lastname: "สมบูรณ์ทรัพย์", lastnameEn: "Sombunthrap",
    nickname: "ขวัญ",
    gender: "หญิง", dob: "2007-02-06",
    nationalId: "4-1787-04007-19-1", passport: "",
    country: "ไทย",
    address: "9 ซ.สุขุมวิท 77 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "091-121-1212", email: "khwanjira@student.kosen.ac.th", lineId: "kwan_design",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "วิศวกรรมคอมพิวเตอร์", year: "2",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-050", prefix: "นาย", prefixEn: "Mr.",
    name: "ชาตรีพล", nameEn: "Chatreephon",
    lastname: "พุ่มเพชร", lastnameEn: "Phumphhet",
    nickname: "ชาต",
    gender: "ชาย", dob: "2008-05-13",
    nationalId: "5-1824-04090-38-4", passport: "",
    country: "ไทย",
    address: "45/2 หมู่ 7 ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี 12120",
    tel: "092-232-2323", email: "chatreephon@student.kosen.ac.th", lineId: "chat_cs",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "ระบบควบคุมอัตโนมัติ", year: "1",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-051", prefix: "นางสาว", prefixEn: "Miss",
    name: "ปณิชา", nameEn: "Panicha",
    lastname: "ถิ่นนคร", lastnameEn: "Thinnakhon",
    nickname: "ปณ",
    gender: "หญิง", dob: "2004-08-20",
    nationalId: "5-1861-04173-57-7", passport: "GU9728351",
    country: "ไทย",
    address: "78 ถ.พหลโยธิน แขวงพญาไท เขตพญาไท กรุงเทพฯ 10400",
    tel: "093-343-3434", email: "panicha@student.kosen.ac.th", lineId: "",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมอิเล็กทรอนิกส์", year: "5",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "การออกแบบ RFIC สำหรับ 5G Sub-6GHz ด้วย CMOS 28nm",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-052", prefix: "นาย", prefixEn: "Mr.",
    name: "ปิยวัฒน์", nameEn: "Piyawat",
    lastname: "หาญกมล", lastnameEn: "Hankamod",
    nickname: "ปิย",
    gender: "ชาย", dob: "2005-11-27",
    nationalId: "5-1898-04256-76-0", passport: "",
    country: "ไทย",
    address: "33 ซ.จรัญสนิทวงศ์ 13 แขวงบางอ้อ เขตบางพลัด กรุงเทพฯ 10700",
    tel: "094-454-4545", email: "piyawat@student.kosen.ac.th", lineId: "piya_ee",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "ปัญญาประดิษฐ์และการเรียนรู้ของเครื่อง", year: "4",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "ระบบ Edge AI สำหรับตรวจสอบคุณภาพผลิตภัณฑ์ในสายการผลิต",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-053", prefix: "นางสาว", prefixEn: "Miss",
    name: "กรรณ์นิการ์", nameEn: "Kannika",
    lastname: "ศรีสมทรัพย์", lastnameEn: "Srisomthrap",
    nickname: "การ์",
    gender: "หญิง", dob: "2006-02-06",
    nationalId: "5-1935-04339-95-3", passport: "",
    country: "ไทย",
    address: "101 ถ.นิมมานเหมินท์ ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200",
    tel: "095-565-5656", email: "kannika@student.kosen.ac.th", lineId: "kan_design",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "วิศวกรรมไฟฟ้ากำลัง", year: "3",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "ระบบตรวจจับ Fault ในสายส่งไฟฟ้าด้วย Machine Learning",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-054", prefix: "นาย", prefixEn: "Mr.",
    name: "นิติพล", nameEn: "Nitiphon",
    lastname: "แจ้งจิตร", lastnameEn: "Jaengjit",
    nickname: "นิติ",
    gender: "ชาย", dob: "2007-05-13",
    nationalId: "5-1972-04422-14-6", passport: "",
    country: "ไทย",
    address: "55/4 หมู่ 2 ต.เชิงดอย อ.ดอยสะเก็ด จ.เชียงใหม่ 50220",
    tel: "096-676-6767", email: "nitiphon@student.kosen.ac.th", lineId: "",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมโทรคมนาคม", year: "2",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-055", prefix: "นางสาว", prefixEn: "Miss",
    name: "พรนภา", nameEn: "Phonnapa",
    lastname: "นาวาวิจักษณ์", lastnameEn: "Nawawichak",
    nickname: "พร",
    gender: "หญิง", dob: "2008-08-20",
    nationalId: "5-2009-04505-33-0", passport: "",
    country: "ไทย",
    address: "8/9 ถ.กาญจนวนิช ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา 90110",
    tel: "097-787-7878", email: "phonnapa@student.kosen.ac.th", lineId: "porn_me",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "วิศวกรรมคอมพิวเตอร์", year: "1",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-056", prefix: "นาย", prefixEn: "Mr.",
    name: "สรวิชญ์", nameEn: "Sorawit",
    lastname: "รัตนะวงศ์ชัย", lastnameEn: "Rattanawongchai",
    nickname: "ศิ",
    gender: "ชาย", dob: "2006-11-27",
    nationalId: "5-2046-04588-52-3", passport: "XF6901186",
    country: "ไทย",
    address: "29 ถ.เจริญกรุง แขวงสี่พระยา เขตบางรัก กรุงเทพฯ 10500",
    tel: "098-898-8989", email: "sorawit@student.kosen.ac.th", lineId: "sit_ee",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "ระบบควบคุมอัตโนมัติ", year: "3",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "การวิเคราะห์คุณภาพไฟฟ้าในระบบจำหน่ายด้วย AI",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "พ้นสภาพ", note: "ขาดการติดต่อ", avatar: null,
  },
  {
    id: "STU-057", prefix: "นางสาว", prefixEn: "Miss",
    name: "สิริยาภรณ์", nameEn: "Siriyaphorn",
    lastname: "มีชัยพร", lastnameEn: "Meechaiphon",
    nickname: "ยา",
    gender: "หญิง", dob: "2005-02-06",
    nationalId: "5-2083-04671-71-6", passport: "",
    country: "ไทย",
    address: "11 ถ.สุขสวัสดิ์ แขวงราษฎร์บูรณะ เขตราษฎร์บูรณะ กรุงเทพฯ 10140",
    tel: "099-909-9090", email: "siriyaphorn@student.kosen.ac.th", lineId: "ya_design",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมอิเล็กทรอนิกส์", year: "4",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "ระบบสื่อสารไร้สายความหน่วงต่ำสำหรับ Industrial IoT บน FPGA",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-058", prefix: "นาย", prefixEn: "Mr.",
    name: "นครินทร์", nameEn: "Nakharin",
    lastname: "ผาสุขเกษม", lastnameEn: "Phasukasem",
    nickname: "นคร",
    gender: "ชาย", dob: "2004-05-13",
    nationalId: "", passport: "DV9370320",
    country: "ญี่ปุ่น",
    address: "1-2-3 Shinjuku, Shinjuku-ku, Tokyo 160-0022",
    tel: "081-141-4141", email: "nakharin@student.kosen.ac.th", lineId: "",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "ปัญญาประดิษฐ์และการเรียนรู้ของเครื่อง", year: "5",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "การเร่งความเร็ว Transformer Inference บน Custom RISC-V Processor",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ได้รับการยกเว้น",
    status: "ฝึกงาน", note: "ฝึกงานที่ LINE MAN Wongnai", avatar: null,
  },
  {
    id: "STU-059", prefix: "นางสาว", prefixEn: "Miss",
    name: "ธัญพร", nameEn: "Thanphon",
    lastname: "สุขสำราญจิต", lastnameEn: "Suksamranjit",
    nickname: "ธัญ",
    gender: "หญิง", dob: "2007-08-20",
    nationalId: "5-2157-04837-09-1", passport: "",
    country: "ไทย",
    address: "22/5 ซ.บางนา-ตราด 40 แขวงบางนา เขตบางนา กรุงเทพฯ 10260",
    tel: "082-252-5252", email: "thanphon@student.kosen.ac.th", lineId: "than_me",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "วิศวกรรมไฟฟ้ากำลัง", year: "2",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-060", prefix: "นาย", prefixEn: "Mr.",
    name: "ประพนธ์วิชญ์", nameEn: "Praphonwit",
    lastname: "เต็มจิต", lastnameEn: "Temjit",
    nickname: "พรหม",
    gender: "ชาย", dob: "2008-11-27",
    nationalId: "6-2194-04920-28-4", passport: "",
    country: "ไทย",
    address: "148 ถ.ขอนแก่น-อุดรธานี ต.ในเมือง อ.เมือง จ.ขอนแก่น 40000",
    tel: "083-363-6363", email: "praphonwit@student.kosen.ac.th", lineId: "phrom_ee",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมโทรคมนาคม", year: "1",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-061", prefix: "นางสาว", prefixEn: "Miss",
    name: "กัลยกร", nameEn: "Kanyakorn",
    lastname: "ชมพูทวีป", lastnameEn: "Chomphuthaweep",
    nickname: "กัล",
    gender: "หญิง", dob: "2004-02-06",
    nationalId: "6-2231-05003-47-7", passport: "NS4074021",
    country: "ไทย",
    address: "12/5 ซ.ลาดพร้าว 71 แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพฯ 10230",
    tel: "084-474-7474", email: "kanyakorn@student.kosen.ac.th", lineId: "",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "วิศวกรรมคอมพิวเตอร์", year: "5",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "Distributed Federated Learning บนอุปกรณ์ IoT ที่มีทรัพยากรจำกัด",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-062", prefix: "นาย", prefixEn: "Mr.",
    name: "อภิวัฒน์", nameEn: "Aphiwat",
    lastname: "ตันพงษ์ศักดิ์", lastnameEn: "Tanphongsak",
    nickname: "อภิ",
    gender: "ชาย", dob: "2006-05-13",
    nationalId: "6-2268-05086-66-0", passport: "",
    country: "ไทย",
    address: "34 ถ.รัชดาภิเษก แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "085-585-8585", email: "aphiwat@student.kosen.ac.th", lineId: "api_cs",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "ระบบควบคุมอัตโนมัติ", year: "3",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "ระบบควบคุมมอเตอร์ Induction แบบ Field Oriented Control",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-063", prefix: "นางสาว", prefixEn: "Miss",
    name: "วรินทร์ธรา", nameEn: "Warinthara",
    lastname: "โชคชัยวัฒน์", lastnameEn: "Chokchaiwat",
    nickname: "วาริ",
    gender: "หญิง", dob: "2005-08-20",
    nationalId: "6-2305-05169-85-3", passport: "",
    country: "ไทย",
    address: "88/3 หมู่ 4 ต.บางแก้ว อ.บางพลี จ.สมุทรปราการ 10540",
    tel: "086-696-9696", email: "warinthara@student.kosen.ac.th", lineId: "wari_me",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมอิเล็กทรอนิกส์", year: "4",
    advisor: "รศ.ดร.สุขสันต์ หิรัญวงษ์",
    project: "การออกแบบ Low-Noise Amplifier สำหรับ Satellite Communication",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-064", prefix: "นาย", prefixEn: "Mr.",
    name: "ธรรมนันท์", nameEn: "Thammanun",
    lastname: "จงรักภักดี", lastnameEn: "Jongrakphakdi",
    nickname: "ธรรม",
    gender: "ชาย", dob: "2007-11-27",
    nationalId: "6-2342-05252-04-6", passport: "",
    country: "ไทย",
    address: "22 ซ.อ่อนนุช 46 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "087-707-7070", email: "thammanun@student.kosen.ac.th", lineId: "",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "ปัญญาประดิษฐ์และการเรียนรู้ของเครื่อง", year: "2",
    advisor: "รศ.ดร.ธนา ลิ้มสุวรรณ",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-065", prefix: "นางสาว", prefixEn: "Miss",
    name: "ตฤณรัตน์", nameEn: "Trinrat",
    lastname: "หวังดีวงศ์", lastnameEn: "Wangdeewong",
    nickname: "ตรี",
    gender: "หญิง", dob: "2008-02-06",
    nationalId: "6-2379-05335-23-9", passport: "",
    country: "ไทย",
    address: "5/1 ถ.พระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "088-818-8181", email: "trinrat@student.kosen.ac.th", lineId: "tree_design",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมไฟฟ้า",
    department: "วิศวกรรมไฟฟ้า", major: "วิศวกรรมไฟฟ้ากำลัง", year: "1",
    advisor: "ผศ.ดร.กานต์ ทิพย์กาญจนา",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-066", prefix: "นาย", prefixEn: "Mr.",
    name: "บรรณสิทธิ์", nameEn: "Bannasit",
    lastname: "อุดมพงศ์", lastnameEn: "Udompong",
    nickname: "บรร",
    gender: "ชาย", dob: "2004-05-13",
    nationalId: "6-2416-05418-42-2", passport: "DD1246856",
    country: "ไทย",
    address: "67 ถ.เพชรบุรีตัดใหม่ แขวงบางกะปิ เขตห้วยขวาง กรุงเทพฯ 10310",
    tel: "089-929-9292", email: "bannasit@student.kosen.ac.th", lineId: "ban_cs",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "ปัญญาประดิษฐ์และการเรียนรู้ของเครื่อง", year: "5",
    advisor: "รศ.ดร.ชวลิต ลิ้มสุวรรณ",
    project: "ระบบ Edge AI สำหรับตรวจสอบคุณภาพผลิตภัณฑ์ในสายการผลิต",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่านการเกณฑ์",
    status: "ฝึกงาน", note: "ฝึกงานที่ SCB Tech X", avatar: null,
  },
  {
    id: "STU-067", prefix: "นางสาว", prefixEn: "Miss",
    name: "ศศิกาญจน์", nameEn: "Sasikan",
    lastname: "นิลวรรณสกุล", lastnameEn: "Nillowansakun",
    nickname: "ศศิ",
    gender: "หญิง", dob: "2006-08-20",
    nationalId: "6-2453-05501-61-5", passport: "",
    country: "ไทย",
    address: "15/8 ซ.นวมินทร์ 42 แขวงคลองกุ่ม เขตบึงกุ่ม กรุงเทพฯ 10230",
    tel: "090-030-3030", email: "sasikan@student.kosen.ac.th", lineId: "",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-KMITL", faculty: "วิศวกรรมอิเล็กทรอนิกส์",
    department: "วิศวกรรมอิเล็กทรอนิกส์", major: "วิศวกรรมอิเล็กทรอนิกส์", year: "3",
    advisor: "รศ.ดร.ปิยะ นาควัชระ",
    project: "การพัฒนา Software Defined Radio สำหรับตรวจสอบสเปกตรัมคลื่นความถี่",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },

  // ── KOSEN-Chulabhorn (STU-068 – STU-101) ─────────────────────────────────
  {
    id: "STU-068", prefix: "นาย", prefixEn: "Mr.",
    name: "ดุลยวัต", nameEn: "Dulyawat",
    lastname: "วังนาเวียง", lastnameEn: "Wangnawieng",
    nickname: "ดุลย์",
    gender: "ชาย", dob: "2005-11-27",
    nationalId: "6-2490-05584-80-8", passport: "",
    country: "ไทย",
    address: "200 ถ.ศรีนครินทร์ แขวงหนองบอน เขตประเวศ กรุงเทพฯ 10250",
    tel: "091-141-1414", email: "dulyawat@student.kosen.ac.th", lineId: "duly_ee",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "ระบบสารสนเทศ", year: "4",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "แอปพลิเคชันวิเคราะห์เสถียรภาพทางการเงินด้วย NLP และ Sentiment Analysis",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "พักการเรียน", note: "", avatar: null,
  },
  {
    id: "STU-069", prefix: "นางสาว", prefixEn: "Miss",
    name: "ปาณิสรา", nameEn: "Panisara",
    lastname: "ทิพย์ประสาท", lastnameEn: "Thipparasat",
    nickname: "ปา",
    gender: "หญิง", dob: "2007-02-06",
    nationalId: "6-2527-05667-99-0", passport: "",
    country: "ไทย",
    address: "9 ซ.สุขุมวิท 77 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "092-252-2525", email: "panisara@student.kosen.ac.th", lineId: "pa_design",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "ฟิสิกส์ประยุกต์", year: "2",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-070", prefix: "นาย", prefixEn: "Mr.",
    name: "ศักดิ์นรินทร์", nameEn: "Saknarin",
    lastname: "มาตรฐาน", lastnameEn: "Mattathan",
    nickname: "ศักดิ์",
    gender: "ชาย", dob: "2008-05-13",
    nationalId: "7-2564-05750-18-3", passport: "",
    country: "ไทย",
    address: "45/2 หมู่ 7 ต.คลองหนึ่ง อ.คลองหลวง จ.ปทุมธานี 12120",
    tel: "093-363-3636", email: "saknarin@student.kosen.ac.th", lineId: "sakda_cs",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "นวัตกรรมการออกแบบ", year: "1",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-071", prefix: "นางสาว", prefixEn: "Miss",
    name: "ดวงพร", nameEn: "Duangphon",
    lastname: "ศรีเพ็ชรงาม", lastnameEn: "Sriphetchngam",
    nickname: "ดวง",
    gender: "หญิง", dob: "2004-08-20",
    nationalId: "7-2601-05833-37-6", passport: "UQ7419691",
    country: "ไทย",
    address: "78 ถ.พหลโยธิน แขวงพญาไท เขตพญาไท กรุงเทพฯ 10400",
    tel: "094-474-4747", email: "duangphon@student.kosen.ac.th", lineId: "",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "วิทยาการคอมพิวเตอร์", year: "5",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "แพลตฟอร์มวิเคราะห์ข้อมูลสุขภาพจากอุปกรณ์สวมใส่ด้วย Cloud Computing",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-072", prefix: "นาย", prefixEn: "Mr.",
    name: "พัทธนันท์", nameEn: "Phatthanun",
    lastname: "ลอยเมฆา", lastnameEn: "Loimeka",
    nickname: "แพท",
    gender: "ชาย", dob: "2006-11-27",
    nationalId: "7-2638-05916-56-9", passport: "",
    country: "ไทย",
    address: "33 ซ.จรัญสนิทวงศ์ 13 แขวงบางอ้อ เขตบางพลัด กรุงเทพฯ 10700",
    tel: "095-585-5858", email: "phatthanun@student.kosen.ac.th", lineId: "pat_ee",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "เคมีประยุกต์", year: "3",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "วัสดุ Thermoelectric ประสิทธิภาพสูงจาก Bismuth Telluride Nanocomposite",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-073", prefix: "นางสาว", prefixEn: "Miss",
    name: "กนกรัตน์", nameEn: "Kanokrat",
    lastname: "มูลประสาท", lastnameEn: "Munprasat",
    nickname: "กนก",
    gender: "หญิง", dob: "2005-02-06",
    nationalId: "7-2675-05999-75-2", passport: "",
    country: "ไทย",
    address: "101 ถ.นิมมานเหมินท์ ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200",
    tel: "096-696-6969", email: "kanokrat@student.kosen.ac.th", lineId: "kanok_design",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "การออกแบบอุตสาหกรรม", year: "4",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "การพัฒนาผลิตภัณฑ์เฟอร์นิเจอร์จากวัสดุรีไซเคิลด้วย Circular Design",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "ฝึกงาน", note: "", avatar: null,
  },
  {
    id: "STU-074", prefix: "นาย", prefixEn: "Mr.",
    name: "ไชยพศ", nameEn: "Chaiyapot",
    lastname: "กำลังเลิศ", lastnameEn: "Kamlangloet",
    nickname: "ชัย",
    gender: "ชาย", dob: "2007-05-13",
    nationalId: "7-2712-06082-94-5", passport: "",
    country: "ไทย",
    address: "55/4 หมู่ 2 ต.เชิงดอย อ.ดอยสะเก็ด จ.เชียงใหม่ 50220",
    tel: "097-707-7979", email: "chaiyapot@student.kosen.ac.th", lineId: "",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "ระบบสารสนเทศ", year: "2",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-075", prefix: "นางสาว", prefixEn: "Miss",
    name: "มนัสนิดา", nameEn: "Manassnida",
    lastname: "รื่นเจริญ", lastnameEn: "Ruecharoen",
    nickname: "แมน",
    gender: "หญิง", dob: "2008-08-20",
    nationalId: "7-2749-06165-13-8", passport: "",
    country: "ไทย",
    address: "8/9 ถ.กาญจนวนิช ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา 90110",
    tel: "098-818-8080", email: "manassnida@student.kosen.ac.th", lineId: "man_me",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "ฟิสิกส์ประยุกต์", year: "1",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-076", prefix: "นาย", prefixEn: "Mr.",
    name: "จิรายุส", nameEn: "Jirayut",
    lastname: "บัวเงิน", lastnameEn: "Buangoen",
    nickname: "จิ",
    gender: "ชาย", dob: "2004-11-27",
    nationalId: "", passport: "KB4592526",
    country: "ญี่ปุ่น",
    address: "1-2-3 Shinjuku, Shinjuku-ku, Tokyo 160-0022",
    tel: "099-919-9191", email: "jirayut@student.kosen.ac.th", lineId: "ji_ee",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "นวัตกรรมการออกแบบ", year: "5",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "นวัตกรรมของเล่นส่งเสริมพัฒนาการเด็กออทิสติกด้วยหลัก Universal Design",
    scholarship: "ทุน จภ.",
    militaryStatus: "ได้รับการยกเว้น",
    status: "ฝึกงาน", note: "ฝึกงานที่ True Digital Group", avatar: null,
  },
  {
    id: "STU-077", prefix: "นางสาว", prefixEn: "Miss",
    name: "สุดาภัทร", nameEn: "Sudaphat",
    lastname: "กุลชัยวัฒน์", lastnameEn: "Kunlachaiwat",
    nickname: "สุดา",
    gender: "หญิง", dob: "2006-02-06",
    nationalId: "7-2823-06331-51-4", passport: "",
    country: "ไทย",
    address: "11 ถ.สุขสวัสดิ์ แขวงราษฎร์บูรณะ เขตราษฎร์บูรณะ กรุงเทพฯ 10140",
    tel: "081-161-6161", email: "sudaphat@student.kosen.ac.th", lineId: "",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "วิทยาการคอมพิวเตอร์", year: "3",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "การพัฒนาระบบ CI/CD อัตโนมัติสำหรับองค์กร DevOps",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-078", prefix: "นาย", prefixEn: "Mr.",
    name: "ณัฐวรรธน์", nameEn: "Nattawat",
    lastname: "วิริยพงศ์", lastnameEn: "Wiriyaphong",
    nickname: "นนท์",
    gender: "ชาย", dob: "2005-05-13",
    nationalId: "7-2860-06414-70-7", passport: "",
    country: "ไทย",
    address: "63 ถ.ราชพฤกษ์ ต.บางรักพัฒนา อ.บางบัวทอง จ.นนทบุรี 11110",
    tel: "082-272-7272", email: "nattawat@student.kosen.ac.th", lineId: "non_cs",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "เคมีประยุกต์", year: "4",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "การสังเคราะห์ Quantum Dot สำหรับ Biosensor ตรวจมะเร็งระยะเริ่มต้น",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-079", prefix: "นางสาว", prefixEn: "Miss",
    name: "วัชราภรณ์", nameEn: "Watcharaphorn",
    lastname: "สมบูรณ์สุข", lastnameEn: "Sombunnsuk",
    nickname: "วัช",
    gender: "หญิง", dob: "2007-08-20",
    nationalId: "7-2897-06497-89-9", passport: "",
    country: "ไทย",
    address: "22/5 ซ.บางนา-ตราด 40 แขวงบางนา เขตบางนา กรุงเทพฯ 10260",
    tel: "083-383-8383", email: "watcharaphorn@student.kosen.ac.th", lineId: "watch_me",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "การออกแบบอุตสาหกรรม", year: "2",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-080", prefix: "นาย", prefixEn: "Mr.",
    name: "ปรมัตถ์", nameEn: "Paramat",
    lastname: "คมสันต์", lastnameEn: "Khomsan",
    nickname: "ปรม",
    gender: "ชาย", dob: "2008-11-27",
    nationalId: "8-2934-06580-08-2", passport: "",
    country: "ไทย",
    address: "148 ถ.ขอนแก่น-อุดรธานี ต.ในเมือง อ.เมือง จ.ขอนแก่น 40000",
    tel: "084-494-9494", email: "paramat@student.kosen.ac.th", lineId: "",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "ระบบสารสนเทศ", year: "1",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-081", prefix: "นางสาว", prefixEn: "Miss",
    name: "อัมพรพรรณ", nameEn: "Amphonphan",
    lastname: "จิตต์ประเสริฐ", lastnameEn: "Jitprasoet",
    nickname: "อัม",
    gender: "หญิง", dob: "2004-02-06",
    nationalId: "8-2971-06663-27-5", passport: "AN1765361",
    country: "ไทย",
    address: "12/5 ซ.ลาดพร้าว 71 แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพฯ 10230",
    tel: "085-505-0505", email: "amphonphan@student.kosen.ac.th", lineId: "am_design",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "ฟิสิกส์ประยุกต์", year: "5",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "การพัฒนา Perovskite Solar Cell ประสิทธิภาพสูงสำหรับสภาพภูมิอากาศร้อนชื้น",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-082", prefix: "นาย", prefixEn: "Mr.",
    name: "มหิทธิ์ชัย", nameEn: "Mahitchai",
    lastname: "สิงหนาม", lastnameEn: "Singhanam",
    nickname: "มหิ",
    gender: "ชาย", dob: "2006-05-13",
    nationalId: "8-3008-06746-46-9", passport: "",
    country: "ไทย",
    address: "34 ถ.รัชดาภิเษก แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "086-616-1616", email: "mahitchai@student.kosen.ac.th", lineId: "mahit_cs",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "นวัตกรรมการออกแบบ", year: "3",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "การออกแบบยูนิฟอร์มอัจฉริยะตรวจสอบสุขภาพแรงงานในพื้นที่อันตราย",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-083", prefix: "นางสาว", prefixEn: "Miss",
    name: "เมธาวดี", nameEn: "Methawadi",
    lastname: "ผลิตทรัพย์", lastnameEn: "Phalisap",
    nickname: "เมธ",
    gender: "หญิง", dob: "2005-08-20",
    nationalId: "8-3045-06829-65-2", passport: "",
    country: "ไทย",
    address: "88/3 หมู่ 4 ต.บางแก้ว อ.บางพลี จ.สมุทรปราการ 10540",
    tel: "087-727-2727", email: "methawadi@student.kosen.ac.th", lineId: "",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "วิทยาการคอมพิวเตอร์", year: "4",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "ระบบ Smart Library ด้วย RFID และการวิเคราะห์พฤติกรรมผู้ใช้",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-084", prefix: "นาย", prefixEn: "Mr.",
    name: "ก้องกิดา", nameEn: "Kongkida",
    lastname: "หน้าใสดี", lastnameEn: "Nasaidi",
    nickname: "ก้อง",
    gender: "ชาย", dob: "2007-11-27",
    nationalId: "8-3082-06912-84-5", passport: "",
    country: "ไทย",
    address: "22 ซ.อ่อนนุช 46 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "088-838-3838", email: "kongkida@student.kosen.ac.th", lineId: "kong_ee",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "เคมีประยุกต์", year: "2",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "",
    scholarship: "ทุน จภ.",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-085", prefix: "นางสาว", prefixEn: "Miss",
    name: "รุ่งอรุณ", nameEn: "Rungarun",
    lastname: "แสนสุขใจ", lastnameEn: "Sansukchai",
    nickname: "รุ่ง",
    gender: "หญิง", dob: "2008-02-06",
    nationalId: "8-3119-06995-03-8", passport: "",
    country: "ไทย",
    address: "5/1 ถ.พระราม 9 แขวงห้วยขวาง เขตห้วยขวาง กรุงเทพฯ 10320",
    tel: "089-949-9494", email: "rungarun@student.kosen.ac.th", lineId: "rung_design",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "การออกแบบอุตสาหกรรม", year: "1",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-086", prefix: "นาย", prefixEn: "Mr.",
    name: "ประกาศชัย", nameEn: "Prakaschai",
    lastname: "เสริมสุขดี", lastnameEn: "Soermsukhdi",
    nickname: "กาศ",
    gender: "ชาย", dob: "2004-05-13",
    nationalId: "8-3156-07078-22-1", passport: "RZ7938196",
    country: "ไทย",
    address: "67 ถ.เพชรบุรีตัดใหม่ แขวงบางกะปิ เขตห้วยขวาง กรุงเทพฯ 10310",
    tel: "090-050-5050", email: "prakaschai@student.kosen.ac.th", lineId: "",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "ระบบสารสนเทศ", year: "5",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "ระบบแนะนำเนื้อหาส่วนบุคคลบน e-Learning Platform ด้วย Collaborative Filtering",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่านการเกณฑ์",
    status: "ฝึกงาน", note: "ฝึกงานที่ Agoda Thailand", avatar: null,
  },
  {
    id: "STU-087", prefix: "นางสาว", prefixEn: "Miss",
    name: "เสาวลักษณ์", nameEn: "Saowarak",
    lastname: "งามพิสุทธิ์", lastnameEn: "Ngamphisut",
    nickname: "เสาว์",
    gender: "หญิง", dob: "2006-08-20",
    nationalId: "8-3193-07161-41-4", passport: "",
    country: "ไทย",
    address: "15/8 ซ.นวมินทร์ 42 แขวงคลองกุ่ม เขตบึงกุ่ม กรุงเทพฯ 10230",
    tel: "091-161-1616", email: "saowarak@student.kosen.ac.th", lineId: "sao_me",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "ฟิสิกส์ประยุกต์", year: "3",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "ระบบตรวจสอบมลพิษทางอากาศด้วย Laser Spectroscopy",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-088", prefix: "นาย", prefixEn: "Mr.",
    name: "ทินภัทร", nameEn: "Thinnaphat",
    lastname: "เกิดสุวรรณ์", lastnameEn: "Koetsuwan",
    nickname: "ทิน",
    gender: "ชาย", dob: "2005-11-27",
    nationalId: "8-3230-07244-60-7", passport: "",
    country: "ไทย",
    address: "200 ถ.ศรีนครินทร์ แขวงหนองบอน เขตประเวศ กรุงเทพฯ 10250",
    tel: "092-272-2727", email: "thinnaphat@student.kosen.ac.th", lineId: "thin_ee",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "นวัตกรรมการออกแบบ", year: "4",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "ระบบส่วนต่อประสาน Haptic Feedback สำหรับการผ่าตัดแบบ Minimally Invasive",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-089", prefix: "นางสาว", prefixEn: "Miss",
    name: "พัณณ์ชิตา", nameEn: "Phanchita",
    lastname: "ประจักษ์ดี", lastnameEn: "Prajukdi",
    nickname: "พัณณ์",
    gender: "หญิง", dob: "2007-02-06",
    nationalId: "8-3267-07327-79-9", passport: "",
    country: "ไทย",
    address: "9 ซ.สุขุมวิท 77 แขวงสวนหลวง เขตสวนหลวง กรุงเทพฯ 10250",
    tel: "093-383-3838", email: "phanchita@student.kosen.ac.th", lineId: "",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "วิทยาการคอมพิวเตอร์", year: "2",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-090", prefix: "นาย", prefixEn: "Mr.",
    name: "รณกฤต", nameEn: "Ronnakrit",
    lastname: "สรรเสริญดี", lastnameEn: "Sansoendi",
    nickname: "รณ",
    gender: "ชาย", dob: "2008-05-13",
    nationalId: "", passport: "DD3876464",
    country: "ญี่ปุ่น",
    address: "7-8 Umeda, Kita-ku, Osaka 530-0001",
    tel: "094-494-4949", email: "ronnakrit@student.kosen.ac.th", lineId: "ron_cs",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "เคมีประยุกต์", year: "1",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-091", prefix: "นางสาว", prefixEn: "Miss",
    name: "จันทร์วิภา", nameEn: "Chanwipa",
    lastname: "ฉ่ำสุวรรณ", lastnameEn: "Chamsuwan",
    nickname: "จันทร์",
    gender: "หญิง", dob: "2004-08-20",
    nationalId: "9-3341-07493-17-5", passport: "GL5111031",
    country: "ไทย",
    address: "78 ถ.พหลโยธิน แขวงพญาไท เขตพญาไท กรุงเทพฯ 10400",
    tel: "095-505-0505", email: "chanwipa@student.kosen.ac.th", lineId: "jan_me",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "การออกแบบอุตสาหกรรม", year: "5",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "การพัฒนาบรรจุภัณฑ์ Active Packaging ยืดอายุผลไม้เมืองร้อน",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "จบการศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-092", prefix: "นาย", prefixEn: "Mr.",
    name: "เอกวิทย์", nameEn: "Ekkawit",
    lastname: "ทรัพย์มณี", lastnameEn: "Saptmanee",
    nickname: "เอก",
    gender: "ชาย", dob: "2006-11-27",
    nationalId: "9-3378-07576-36-8", passport: "",
    country: "ไทย",
    address: "33 ซ.จรัญสนิทวงศ์ 13 แขวงบางอ้อ เขตบางพลัด กรุงเทพฯ 10700",
    tel: "096-616-6161", email: "ekkawit@student.kosen.ac.th", lineId: "",
    prevSchool: "กำเนิดวิทย์ (KVIS)",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "ระบบสารสนเทศ", year: "3",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "แพลตฟอร์มวิเคราะห์ข้อมูลสุขภาพจากอุปกรณ์สวมใส่ด้วย Cloud Computing",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-093", prefix: "นางสาว", prefixEn: "Miss",
    name: "สุรีมาศ", nameEn: "Surimat",
    lastname: "ณ นครพนม", lastnameEn: "Na Nakhonphanom",
    nickname: "สุรี",
    gender: "หญิง", dob: "2005-02-06",
    nationalId: "9-3415-07659-55-1", passport: "",
    country: "ไทย",
    address: "101 ถ.นิมมานเหมินท์ ต.สุเทพ อ.เมือง จ.เชียงใหม่ 50200",
    tel: "097-727-7272", email: "surimat@student.kosen.ac.th", lineId: "sure_design",
    prevSchool: "เตรียมอุดมศึกษา",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "ฟิสิกส์ประยุกต์", year: "4",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "วัสดุ Thermoelectric ประสิทธิภาพสูงจาก Bismuth Telluride Nanocomposite",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-094", prefix: "นาย", prefixEn: "Mr.",
    name: "ยุทธภูมิ", nameEn: "Yutthaphum",
    lastname: "แข็งการ", lastnameEn: "Khaengkan",
    nickname: "ยุทธ",
    gender: "ชาย", dob: "2007-05-13",
    nationalId: "9-3452-07742-74-4", passport: "",
    country: "ไทย",
    address: "55/4 หมู่ 2 ต.เชิงดอย อ.ดอยสะเก็ด จ.เชียงใหม่ 50220",
    tel: "098-838-8383", email: "yutthaphum@student.kosen.ac.th", lineId: "yut_cs",
    prevSchool: "สวนกุหลาบวิทยาลัย",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "นวัตกรรมการออกแบบ", year: "2",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ยังไม่ถึงเกณฑ์",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-095", prefix: "นางสาว", prefixEn: "Miss",
    name: "หทัยภัทร", nameEn: "Hataiphat",
    lastname: "ปานแก้วนวล", lastnameEn: "Pankaewnuan",
    nickname: "หทัย",
    gender: "หญิง", dob: "2008-08-20",
    nationalId: "9-3489-07825-93-7", passport: "",
    country: "ไทย",
    address: "8/9 ถ.กาญจนวนิช ต.หาดใหญ่ อ.หาดใหญ่ จ.สงขลา 90110",
    tel: "099-949-9494", email: "hataiphat@student.kosen.ac.th", lineId: "",
    prevSchool: "บดินทรเดชา (สิงห์ สิงหเสนี)",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "วิทยาการคอมพิวเตอร์", year: "1",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-096", prefix: "นาย", prefixEn: "Mr.",
    name: "ไพบูลย์", nameEn: "Phaibun",
    lastname: "ศิริวงษ์งาม", lastnameEn: "Siriwongngam",
    nickname: "ไพ",
    gender: "ชาย", dob: "2004-11-27",
    nationalId: "9-3526-07908-12-0", passport: "XX2283866",
    country: "ไทย",
    address: "29 ถ.เจริญกรุง แขวงสี่พระยา เขตบางรัก กรุงเทพฯ 10500",
    tel: "081-191-9191", email: "phaibun@student.kosen.ac.th", lineId: "pai_ee",
    prevSchool: "เตรียมอุดมศึกษาพัฒนาการ",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "เคมีประยุกต์", year: "5",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "Nanocomposite เชิงกลสำหรับวัสดุป้องกันรังสีในทางการแพทย์",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่านการเกณฑ์",
    status: "ฝึกงาน", note: "ฝึกงานที่ PTT Global Chemical", avatar: null,
  },
  {
    id: "STU-097", prefix: "นางสาว", prefixEn: "Miss",
    name: "ภคพร", nameEn: "Phakaphon",
    lastname: "วิสุทธิ์ศรี", lastnameEn: "Wisutsri",
    nickname: "ภค",
    gender: "หญิง", dob: "2006-02-06",
    nationalId: "9-3563-07991-31-3", passport: "",
    country: "ไทย",
    address: "11 ถ.สุขสวัสดิ์ แขวงราษฎร์บูรณะ เขตราษฎร์บูรณะ กรุงเทพฯ 10140",
    tel: "082-202-0202", email: "phakaphon@student.kosen.ac.th", lineId: "pak_design",
    prevSchool: "ศรีอยุธยา ในพระอุปถัมภ์ฯ",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "การออกแบบอุตสาหกรรม", year: "3",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "นวัตกรรมของเล่นส่งเสริมพัฒนาการเด็กออทิสติกด้วยหลัก Universal Design",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-098", prefix: "นาย", prefixEn: "Mr.",
    name: "คมกฤช", nameEn: "Khomkrit",
    lastname: "ดาวเรืองแสง", lastnameEn: "Dawrueangsuang",
    nickname: "คม",
    gender: "ชาย", dob: "2005-05-13",
    nationalId: "9-3600-08074-50-6", passport: "",
    country: "ไทย",
    address: "63 ถ.ราชพฤกษ์ ต.บางรักพัฒนา อ.บางบัวทอง จ.นนทบุรี 11110",
    tel: "083-313-1313", email: "khomkrit@student.kosen.ac.th", lineId: "",
    prevSchool: "สาธิตมหาวิทยาลัยเกษตรศาสตร์",
    university: "KOSEN-Chulabhorn", faculty: "เทคโนโลยีสารสนเทศ",
    department: "เทคโนโลยีสารสนเทศ", major: "ระบบสารสนเทศ", year: "4",
    advisor: "ผศ.ดร.ปริญญา มีสุวรรณ",
    project: "การพัฒนาระบบ CI/CD อัตโนมัติสำหรับองค์กร DevOps",
    scholarship: "ทุน 3 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-099", prefix: "นางสาว", prefixEn: "Miss",
    name: "ลภัสรดา", nameEn: "Lapatsrada",
    lastname: "สุขประเสริฐพร", lastnameEn: "Sukhprasoetphon",
    nickname: "ลภัส",
    gender: "หญิง", dob: "2007-08-20",
    nationalId: "9-3637-08157-69-8", passport: "",
    country: "ไทย",
    address: "22/5 ซ.บางนา-ตราด 40 แขวงบางนา เขตบางนา กรุงเทพฯ 10260",
    tel: "084-424-2424", email: "lapatsrada@student.kosen.ac.th", lineId: "la_me",
    prevSchool: "สาธิตจุฬาลงกรณ์มหาวิทยาลัย",
    university: "KOSEN-Chulabhorn", faculty: "วิทยาศาสตร์ประยุกต์",
    department: "วิทยาศาสตร์ประยุกต์", major: "ฟิสิกส์ประยุกต์", year: "2",
    advisor: "รศ.ดร.ศิริลักษณ์ ประสงค์",
    project: "",
    scholarship: "ทุน 5 ปี",
    militaryStatus: "-",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-100", prefix: "นาย", prefixEn: "Mr.",
    name: "ศิวนัฐ", nameEn: "Siwanath",
    lastname: "พงศ์ประดิษฐ์", lastnameEn: "Phongpradit",
    nickname: "ศิวะ",
    gender: "ชาย", dob: "2006-11-27",
    nationalId: "1-3674-08240-88-1", passport: "",
    country: "ไทย",
    address: "148 ถ.ขอนแก่น-อุดรธานี ต.ในเมือง อ.เมือง จ.ขอนแก่น 40000",
    tel: "085-535-3535", email: "siwanath@student.kosen.ac.th", lineId: "siwa_ee",
    prevSchool: "อัสสัมชัญ",
    university: "KOSEN-Chulabhorn", faculty: "การออกแบบและนวัตกรรม",
    department: "การออกแบบและนวัตกรรม", major: "นวัตกรรมการออกแบบ", year: "3",
    advisor: "รศ.ดร.ปิยะนุช เงินคล้าย",
    project: "นวัตกรรมอุปกรณ์ช่วยเหลือผู้พิการแขนขาด้วยการพิมพ์ 3 มิติและระบบ EMG",
    scholarship: "ทุน จภ.",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
  {
    id: "STU-101", prefix: "นาย", prefixEn: "Mr.",
    name: "รัฐสรรค์", nameEn: "Rattasan",
    lastname: "เอกอัครชวกิตติ์", lastnameEn: "Ekkakkhrachawakitt",
    nickname: "โดโด้",
    gender: "ชาย", dob: "2006-02-06",
    nationalId: "1-3711-08323-07-4", passport: "NJ8456701",
    country: "ไทย",
    address: "12/5 ซ.ลาดพร้าว 71 แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพฯ 10230",
    tel: "085-334-6678", email: "rattasan@student.kosen.ac.th", lineId: "dodo",
    prevSchool: "มหิดลวิทยานุสรณ์",
    university: "KOSEN-Chulabhorn", faculty: "วิศวกรรมคอมพิวเตอร์",
    department: "วิศวกรรมคอมพิวเตอร์", major: "วิศวกรรมคอมพิวเตอร์", year: "3",
    advisor: "ผศ.ดร.พรชัย ชุณหจินดา",
    project: "ระบบ Edge AI สำหรับตรวจสอบคุณภาพผลิตภัณฑ์ในสายการผลิต",
    scholarship: "ทุน 2 ปี",
    militaryStatus: "ผ่อนผัน",
    status: "กำลังศึกษา", note: "", avatar: null,
  },
];

// ── Address parser ────────────────────────────────────────────
function parseThaAddress(addr) {
  if (!addr) return { houseNo: "", subdistrict: "", district: "", province: "", postalCode: "" };
  const postalMatch = addr.match(/(\d{5})\s*$/);
  const postalCode = postalMatch ? postalMatch[1] : "";
  const subdistrictMatch = addr.match(/(?:แขวง|ต\.)([^\s,]+)/);
  const subdistrict = subdistrictMatch ? subdistrictMatch[1] : "";
  const districtMatch = addr.match(/(?:เขต|อ\.)([^\s,]+)/);
  const district = districtMatch ? districtMatch[1] : "";
  let province = "";
  if (addr.includes("กรุงเทพ")) {
    province = "กรุงเทพมหานคร";
  } else {
    const m = addr.match(/จ\.([^\s\d,]+)/);
    if (m) province = m[1];
  }
  const firstKw = addr.search(/\s(?:แขวง|เขต|ต\.|อ\.|จ\.)/);
  const houseNo = firstKw > 0 ? addr.slice(0, firstKw).trim() : addr;
  return { houseNo, subdistrict, district, province, postalCode };
}

// ── Known JP address structures ───────────────────────────────
const JP_ADDR_MAP = {
  "4-5-6 Shibuya, Shibuya-ku, Tokyo 150-0002":   { postalCode: "150-0002", prefecture: "Tokyo", city: "Shibuya-ku",  streetAddress: "4-5-6 Shibuya",  building: "" },
  "7-8 Umeda, Kita-ku, Osaka 530-0001":          { postalCode: "530-0001", prefecture: "Osaka", city: "Kita-ku",     streetAddress: "7-8 Umeda",       building: "" },
  "1-2-3 Shinjuku, Shinjuku-ku, Tokyo 160-0022": { postalCode: "160-0022", prefecture: "Tokyo", city: "Shinjuku-ku", streetAddress: "1-2-3 Shinjuku",  building: "" },
};

// Thai home address for JP-resident students
const JP_STUDENT_HOME_TH = {
  "STU-008": { houseNo: "45 ซ.พหลโยธิน 24",       subdistrict: "จันทรเกษม",     district: "จตุจักร",     province: "กรุงเทพมหานคร", postalCode: "10900" },
  "STU-020": { houseNo: "12/3 ถ.เอกมัย",           subdistrict: "คลองตัน",       district: "วัฒนา",       province: "กรุงเทพมหานคร", postalCode: "10110" },
  "STU-036": { houseNo: "77 ถ.สุขุมวิท 71",         subdistrict: "พระโขนงเหนือ",  district: "วัฒนา",       province: "กรุงเทพมหานคร", postalCode: "10110" },
  "STU-058": { houseNo: "90/5 ซ.ลาดพร้าว 101",     subdistrict: "คลองจั่น",      district: "บางกะปิ",    province: "กรุงเทพมหานคร", postalCode: "10240" },
  "STU-076": { houseNo: "25 ถ.เพชรบุรีตัดใหม่",    subdistrict: "มักกะสัน",      district: "ราชเทวี",    province: "กรุงเทพมหานคร", postalCode: "10400" },
};

// Japanese university enrollments for exchange students
const JP_UNIV_ENROLLMENT = {
  "STU-008": { university: "Tokyo Institute of Technology (TITECH)", studentId: "24M50008", univEmail: "24m50008@student.titech.ac.jp",     faculty: "School of Engineering",                          department: "Dept. of Mechanical Engineering",     major: "Mechanical Engineering", year: "1", advisor: "Prof. Tanaka Hiroshi",  project: "" },
  "STU-020": { university: "Waseda University",                      studentId: "1W200020", univEmail: "1w200020@moegi.waseda.jp",          faculty: "School of Advanced Science and Engineering",      department: "Dept. of Applied Chemistry",          major: "Applied Chemistry",       year: "4", advisor: "Prof. Kobayashi Ryo",   project: "" },
  "STU-036": { university: "Osaka University",                       studentId: "24EE0036", univEmail: "24ee0036@ist.osaka-u.ac.jp",        faculty: "School of Engineering Science",                   department: "Dept. of Electronic Physics",         major: "Electronics",             year: "3", advisor: "Prof. Yamamoto Kenji",  project: "" },
  "STU-058": { university: "University of Tokyo (UTokyo)",           studentId: "24G50058", univEmail: "24g50058@g.ecc.u-tokyo.ac.jp",     faculty: "Graduate School of Information Science & Tech.", department: "Dept. of Computer Science",           major: "Computer Science",        year: "2", advisor: "Prof. Suzuki Masato",   project: "" },
  "STU-076": { university: "Kyoto University",                       studentId: "24K00076", univEmail: "24k00076@st.design.kyoto-u.ac.jp", faculty: "Graduate School of Design",                       department: "Dept. of Living & Industrial Design", major: "Design Innovation",       year: "2", advisor: "Prof. Nakamura Yuko",   project: "" },
};

// StudentId counter per (prefix+yearCode)
const _counters = {};
function genStudentId(uni, year) {
  const prefix = { "KOSEN-KMUTT": "KM", "KOSEN-KMITL": "KL", "KOSEN-Chulabhorn": "KC" }[uni] || "KS";
  const yearCode = { "1": "68", "2": "67", "3": "66", "4": "65", "5": "64" }[year] || "66";
  const key = prefix + yearCode;
  _counters[key] = (_counters[key] || 0) + 1;
  return `${prefix}${yearCode}${String(_counters[key]).padStart(3, "0")}`;
}

const UNI_EMAIL_DOMAIN = {
  "KOSEN-KMUTT":       "kmutt.ac.th",
  "KOSEN-KMITL":       "kmitl.ac.th",
  "KOSEN-Chulabhorn":  "ra.ac.th",
};

function buildStudents(raw) {
  return raw.map((s) => {
    // ── enrollments ──
    let enrollments = s.enrollments;
    if (!enrollments) {
      const sid    = genStudentId(s.university, s.year);
      const domain = UNI_EMAIL_DOMAIN[s.university] || "kosen.ac.th";
      const first  = {
        university:  s.university  ?? "",
        studentId:   sid,
        univEmail:   `${sid.toLowerCase()}@student.${domain}`,
        faculty:     s.faculty     ?? "",
        department:  s.department  ?? "",
        major:       s.major       ?? "",
        year:        s.year        ?? "",
        advisor:     s.advisor     ?? "",
        project:     s.project     ?? "",
      };
      const jpEnroll = JP_UNIV_ENROLLMENT[s.id];
      enrollments = jpEnroll ? [first, jpEnroll] : [first];
    }

    // ── addresses ──
    let addresses = s.addresses;
    if (!addresses) {
      const isJP  = s.country === "ญี่ปุ่น";
      const jpData = JP_ADDR_MAP[s.address] ?? null;
      const homeTh = JP_STUDENT_HOME_TH[s.id] ?? null;

      const th = isJP
        ? (homeTh ?? { houseNo: "", subdistrict: "", district: "", province: "", postalCode: "" })
        : parseThaAddress(s.address ?? "");
      const jp = isJP && jpData
        ? jpData
        : { postalCode: "", prefecture: "", city: "", streetAddress: "", building: "" };

      addresses = { th, jp };
    }

    return { ...s, enrollments, addresses };
  });
}

export const DEFAULT_STUDENTS = buildStudents(RAW_STUDENTS);
